#include "Gameplay/TraceTracer.h"

#include "Camera/PlayerCameraManager.h"
#include "Components/SceneComponent.h"
#include "Containers/Ticker.h"
#include "Engine/Engine.h"
#include "HAL/IConsoleManager.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "Math/RotationMatrix.h"
#include "Math/UnrealMathUtility.h"
#include "UObject/ConstructorHelpers.h"

#include "Trace.h"
#include "TraceSettings.h"

namespace
{
	/**
	 * Where the local viewer's eye is, or false if there is nobody looking.
	 *
	 * Used only to decide whether this beam is being drawn practically inside the shooter's own
	 * camera, which is what the standoff exists to handle. The camera manager (not the pawn) is
	 * asked because the spring arm's collision probe and the first/third person view blend both move
	 * the real eye, and it is the REAL eye the flash would be blinding.
	 */
	bool GetLocalView(const UWorld* World, FVector& OutLocation, FRotator& OutRotation)
	{
		if (World == nullptr)
		{
			return false;
		}

		for (FConstPlayerControllerIterator It = World->GetPlayerControllerIterator(); It; ++It)
		{
			const APlayerController* PC = It->Get();
			if (PC == nullptr || !PC->IsLocalController() || PC->PlayerCameraManager == nullptr)
			{
				continue;
			}
			OutLocation = PC->PlayerCameraManager->GetCameraLocation();
			OutRotation = PC->PlayerCameraManager->GetCameraRotation();
			return true;
		}
		return false;
	}
} // namespace

ATraceTracer::ATraceTracer()
{
	// Ticks for one sixth of a second to drive the fade, then deletes itself.
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = true;

	// Cosmetic-only: each machine spawns its own, so this must never go on the wire.
	bReplicates = false;
	SetCanBeDamaged(false);
	InitialLifeSpan = TracerLifeSeconds;

	EffectRoot = CreateDefaultSubobject<USceneComponent>(TEXT("EffectRoot"));
	SetRootComponent(EffectRoot);
	EffectRoot->SetMobility(EComponentMobility::Movable);

	// Constructor-time FObjectFinders (not runtime loads) so the cooker keeps these assets.
	static ConstructorHelpers::FObjectFinder<UStaticMesh> CylinderFinder(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"));
	static ConstructorHelpers::FObjectFinder<UStaticMesh> SphereFinder(TEXT("/Engine/BasicShapes/Sphere.Sphere"));

	// M_TraceNeon is generated by Scripts/generate_content.py into a gitignored content path, so a
	// fresh clone that has not run the generator legitimately does not have it. FObjectFinder logs
	// the miss and we fall back to BasicShapeMaterial: the beam loses its glow but the game plays.
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> NeonFinder(TEXT("/Game/Generated/Materials/M_TraceNeon.M_TraceNeon"));
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> AdditiveFinder(TEXT("/Engine/EngineMaterials/EmissiveMeshMaterial.EmissiveMeshMaterial"));
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> BasicFinder(TEXT("/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"));

	if (NeonFinder.Succeeded())
	{
		NeonMaterial = NeonFinder.Object;
	}
	if (AdditiveFinder.Succeeded())
	{
		AdditiveMaterial = AdditiveFinder.Object;
	}
	if (BasicFinder.Succeeded())
	{
		FallbackMaterial = BasicFinder.Object;
	}

	// One lambda's worth of shared setup: every piece of this effect is visual-only, collisionless,
	// shadowless and decal-free. Getting any of those wrong on a thing that spawns 80 times a second
	// is a performance bug, and a colliding tracer would break hitscan outright.
	auto MakePiece = [this](const TCHAR* Name, UStaticMesh* Mesh) -> UStaticMeshComponent*
	{
		UStaticMeshComponent* Component = CreateDefaultSubobject<UStaticMeshComponent>(Name);
		Component->SetupAttachment(EffectRoot);
		Component->SetMobility(EComponentMobility::Movable);
		Component->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		Component->SetCollisionProfileName(TEXT("NoCollision"));
		Component->SetGenerateOverlapEvents(false);
		Component->SetCastShadow(false);
		Component->bReceivesDecals = false;
		Component->bUseAsOccluder = false;
		if (Mesh != nullptr)
		{
			Component->SetStaticMesh(Mesh);
		}
		return Component;
	};

	UStaticMesh* Cylinder = CylinderFinder.Succeeded() ? CylinderFinder.Object : nullptr;
	UStaticMesh* Sphere = SphereFinder.Succeeded() ? SphereFinder.Object : nullptr;

	BeamCore    = MakePiece(TEXT("BeamCore"), Cylinder);
	BeamSheath  = MakePiece(TEXT("BeamSheath"), Cylinder);
	MuzzleFlash = MakePiece(TEXT("MuzzleFlash"), Sphere);

	// No ImpactFlash: spec v4 §4 deleted the sphere at the far end of the beam. The Sphere mesh is
	// still loaded above because the muzzle flash uses it.
}

ATraceTracer* ATraceTracer::Spawn(UWorld* World, const FVector& From, const FVector& To, const FLinearColor& Color, bool bImpacted)
{
	if (World == nullptr)
	{
		return nullptr;
	}

	// A headless server has nobody to show this to.
	if (World->GetNetMode() == NM_DedicatedServer)
	{
		return nullptr;
	}

	if (From.ContainsNaN() || To.ContainsNaN())
	{
		return nullptr;
	}

	if ((To - From).SizeSquared() < static_cast<double>(MinTracerLengthUU) * static_cast<double>(MinTracerLengthUU))
	{
		return nullptr;
	}

	FActorSpawnParameters SpawnParams;
	SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
	SpawnParams.ObjectFlags |= RF_Transient;

	ATraceTracer* Tracer = World->SpawnActor<ATraceTracer>(ATraceTracer::StaticClass(), FTransform::Identity, SpawnParams);
	if (Tracer != nullptr)
	{
		Tracer->InitTracer(From, To, Color, bImpacted);
	}
	return Tracer;
}

UMaterialInstanceDynamic* ATraceTracer::MakeMID(UStaticMeshComponent* Mesh, UMaterialInterface* Material)
{
	if (Mesh == nullptr || Material == nullptr)
	{
		return nullptr;
	}
	return Mesh->CreateDynamicMaterialInstance(0, Material);
}

void ATraceTracer::SetMIDColor(UMaterialInstanceDynamic* MID, const FLinearColor& Color, float Intensity, bool bGlowScalar)
{
	if (MID == nullptr)
	{
		return;
	}

	if (bGlowScalar)
	{
		// M_TraceNeon: EmissiveColor = Color * Glow, with Color a plain 0..1 hue and Glow the
		// multiplier that pushes it past the bloom threshold. This is exactly how the arena builder
		// and the trail drive the same material, and matching them matters: a vector parameter is
		// the wrong place to carry a value of 30, and the shipped, proven idiom is the scalar.
		MID->SetVectorParameterValue(TEXT("Color"), Color);
		MID->SetScalarParameterValue(TEXT("Glow"), FMath::Max(0.f, Intensity));

		// BasicShapeMaterial fallback: lit, "Color" only, no Glow. Nothing extra to do - the line
		// above already gave it the right hue, it just will not glow.
		return;
	}

	// EmissiveMeshMaterial (the additive sheath) has no Glow scalar, so intensity has to ride in
	// the colour itself.
	MID->SetVectorParameterValue(TEXT("Color"), Color * FMath::Max(0.f, Intensity));
}

void ATraceTracer::InitTracer(const FVector& From, const FVector& To, const FLinearColor& Color, bool bImpacted)
{
	FVector Delta = To - From;
	double Length = Delta.Size();
	if (Length < static_cast<double>(MinTracerLengthUU))
	{
		return;
	}
	const FVector Dir = Delta / Length;

	// --- first person treatment (see the class comment) -----------------------------------------
	//
	// The point-blank impact-pop dimming that used to live here is gone with the impact sphere it
	// protected against. Nothing else in this effect is large, unlit and drawn at the far end of the
	// ray, so there is no longer a whiteout to defend against there.
	FVector BeamStart = From;
	FVector ViewLocation = FVector::ZeroVector;
	FRotator ViewRotation = FRotator::ZeroRotator;
	if (GetLocalView(GetWorld(), ViewLocation, ViewRotation))
	{
		const double ToEye = FVector::Dist(ViewLocation, From);
		if (ToEye < FirstPersonProximityUU)
		{
			// Never push the start past the impact: on a shot into a wall 30 uu away the beam would
			// otherwise invert. Leave at least a quarter of the shot to draw.
			const double Standoff = FMath::Min(static_cast<double>(FirstPersonStandoffUU), Length * 0.75);

			// Out of the near field, then across into the viewmodel's corner of the screen. The
			// offset is scaled by how much standoff we actually got, so a short shot into a nearby
			// wall does not fling the beam sideways past its own impact point.
			const double OffsetScale = Standoff / static_cast<double>(FirstPersonStandoffUU);
			const FRotationMatrix ViewAxes(ViewRotation);
			BeamStart = From
				+ Dir * Standoff
				+ ViewAxes.GetScaledAxis(EAxis::Y) * (FirstPersonRightOffsetUU * OffsetScale)
				- ViewAxes.GetScaledAxis(EAxis::Z) * (FirstPersonDownOffsetUU * OffsetScale);
		}
	}

	// Re-derive from the (possibly moved) start so the beam still lands exactly on the impact point.
	// This is the whole trick: the near end moves to the gun, the far end does not move at all, and
	// the beam therefore converges on the crosshair.
	Delta = To - BeamStart;
	Length = Delta.Size();
	if (Length < static_cast<double>(MinTracerLengthUU))
	{
		return;
	}
	const FVector BeamDir = Delta / Length;

	// --- width (spec v4 §4) ---------------------------------------------------------------------
	//
	// Read fresh per shot, so dragging the Tracer sliders in Project Settings retunes the beam with
	// PIE running - that is the point of moving these out of this file's constants.
	//
	// Radius in, diameter out: /Engine/BasicShapes primitives are 100 uu ACROSS, so a diameter is
	// what divides cleanly into a mesh scale. The doubling happens exactly here so nothing further
	// down has to remember which unit it is holding.
	const UTraceSettings& Settings = UTraceSettings::Get();

	const float CoreRadiusMin = FMath::Clamp(Settings.TracerRadiusMinUU, MinSafeRadiusUU, MaxSafeRadiusUU);
	const float CoreRadiusMax = FMath::Clamp(Settings.TracerRadiusMaxUU, CoreRadiusMin, MaxSafeRadiusUU);
	const float CoreRadius = FMath::Clamp(
		static_cast<float>(Length) * FMath::Max(0.f, Settings.TracerRadiusPerLength),
		CoreRadiusMin, CoreRadiusMax);

	CoreDiameter = 2.f * CoreRadius;
	SheathDiameter = CoreDiameter * FMath::Max(1.f, Settings.TracerSheathRadiusRatio);
	MuzzleDiameter = 2.f * FMath::Clamp(Settings.TracerMuzzleRadiusUU, MinSafeRadiusUU, MaxSafeRadiusUU);

	// Local +Z runs down the shot, so every piece can be placed by its distance along the beam.
	SetActorLocationAndRotation(BeamStart, FRotationMatrix::MakeFromZ(BeamDir).ToQuat());

	ShotColor = Color;
	HotColor = FMath::Lerp(Color, FLinearColor::White, HotColorWhiteMix);

	const double HalfLength = Length * 0.5;
	const double LengthScale = Length / static_cast<double>(BasicShapeExtentUU);

	// --- beam core ------------------------------------------------------------------------------
	if (BeamCore != nullptr)
	{
		BeamCore->SetRelativeLocation(FVector(0.0, 0.0, HalfLength));
		CoreMID = MakeMID(BeamCore, (NeonMaterial != nullptr) ? NeonMaterial.Get() : FallbackMaterial.Get());
		if (BeamCore->GetStaticMesh() == nullptr)
		{
			UE_LOG(LogTraceGame, Verbose, TEXT("ATraceTracer: /Engine/BasicShapes/Cylinder did not resolve; beam will be invisible."));
		}
	}

	// --- beam sheath ----------------------------------------------------------------------------
	// Additive or nothing. An OPAQUE sheath would swallow the core it is supposed to surround, which
	// looks worse than having no sheath at all, so if the additive material is missing this beat is
	// simply dropped and the core plus bloom carries the effect.
	if (BeamSheath != nullptr)
	{
		if (AdditiveMaterial != nullptr)
		{
			BeamSheath->SetRelativeLocation(FVector(0.0, 0.0, HalfLength));
			SheathMID = MakeMID(BeamSheath, AdditiveMaterial.Get());
		}
		else
		{
			BeamSheath->SetVisibility(false);
		}
	}

	// --- muzzle flash ---------------------------------------------------------------------------
	// Not the sphere spec v4 §4 removed - that one was at the far end. This is the one on the
	// viewmodel, and it is what makes a first-person shot visible at all, so it is switchable rather
	// than deleted.
	bMuzzleVisible = Settings.bTracerMuzzleFlash && (Length >= MinLengthForMuzzleFlashUU);
	if (MuzzleFlash != nullptr)
	{
		if (bMuzzleVisible)
		{
			MuzzleFlash->SetRelativeLocation(FVector::ZeroVector);
			MuzzleMID = MakeMID(MuzzleFlash, (NeonMaterial != nullptr) ? NeonMaterial.Get() : FallbackMaterial.Get());
		}
		else
		{
			MuzzleFlash->SetVisibility(false);
		}
	}

	// NO IMPACT POP. Spec v4 §4: "Remove the sphere from the end of the bullet tracer hitscan
	// animation, so it's just a bullet trace." The beam still terminates exactly on the impact
	// point, which is the information the sphere was covering up. bImpacted is now unused; see the
	// note on Spawn() in the header for why the parameter survives.
	(void)bImpacted;

	// Cache the length-driven scale on the components that need it, then let ApplyFade own the rest.
	if (BeamCore != nullptr)
	{
		BeamCore->SetRelativeScale3D(FVector(1.0, 1.0, LengthScale));
	}
	if (BeamSheath != nullptr)
	{
		BeamSheath->SetRelativeScale3D(FVector(1.0, 1.0, LengthScale));
	}

	// Frame one must already look right: this is hitscan, so there is no state before "fully drawn".
	ApplyFade(0.f);

	// VERBOSE ON PURPOSE - this fires up to ~80 times a second in a full match. Enable it with
	// "log LogTraceGame Verbose" when the beam needs inspecting; do not conclude from its silence
	// that the tracer is not spawning. (Trace.TestBeam logs at Display and is the better probe.)
	UE_LOG(LogTraceGame, Verbose,
		TEXT("TRACER: start=%s len=%.0f coreD=%.2f sheathD=%.2f muzzleD=%.2f coreMat=%s coreParent=%s bounds=%s r=%.0f vis=%d sheathMat=%s"),
		*BeamStart.ToCompactString(), Length, CoreDiameter, SheathDiameter, MuzzleDiameter,
		(BeamCore != nullptr) ? *GetNameSafe(BeamCore->GetMaterial(0)) : TEXT("-"),
		(CoreMID != nullptr) ? *GetNameSafe(CoreMID->Parent) : TEXT("-"),
		(BeamCore != nullptr) ? *BeamCore->Bounds.Origin.ToCompactString() : TEXT("-"),
		(BeamCore != nullptr) ? BeamCore->Bounds.SphereRadius : 0.f,
		(BeamCore != nullptr && BeamCore->IsVisible()) ? 1 : 0,
		(BeamSheath != nullptr) ? *GetNameSafe(BeamSheath->GetMaterial(0)) : TEXT("-"));
}

void ATraceTracer::ApplyFade(float Alpha)
{
	Alpha = FMath::Clamp(Alpha, 0.f, 1.f);

	// Ease-out on intensity: full brightness on arrival, then a fast drop with a short tail. That
	// asymmetry is what reads as "weighty" rather than "a light switch".
	const float Fade = FMath::Pow(1.f - Alpha, 2.2f);

	const double DiameterScale = 1.0 / static_cast<double>(BasicShapeExtentUU);

	// --- core: stays sharp, thins as it dies ----------------------------------------------------
	// Gated on the COMPONENT, not on the MID: if no material resolved at all we still want the
	// geometry at the right thickness rather than a 100 uu wide default cylinder.
	if (BeamCore != nullptr)
	{
		const double Thickness = CoreDiameter * (0.35 + 0.65 * Fade) * DiameterScale;
		const FVector Scale = BeamCore->GetRelativeScale3D();
		BeamCore->SetRelativeScale3D(FVector(Thickness, Thickness, Scale.Z));
		SetMIDColor(CoreMID, HotColor, CoreIntensity * Fade, /*bGlowScalar=*/true);
	}

	// --- sheath: collapses inward faster than the core, so the beam visibly tightens ------------
	if (BeamSheath != nullptr && SheathMID != nullptr)
	{
		const float SheathFade = Fade * Fade;
		const double Thickness = SheathDiameter * (0.25 + 0.75 * SheathFade) * DiameterScale;
		const FVector Scale = BeamSheath->GetRelativeScale3D();
		BeamSheath->SetRelativeScale3D(FVector(Thickness, Thickness, Scale.Z));
		SetMIDColor(SheathMID, ShotColor, SheathIntensity * SheathFade, /*bGlowScalar=*/false);
	}

	// --- muzzle: brightest thing on screen for a moment, gone before the beam is -----------------
	if (bMuzzleVisible && MuzzleFlash != nullptr)
	{
		const float MuzzleAlpha = FMath::Clamp(Alpha / MuzzleFlashLifeFraction, 0.f, 1.f);
		const float MuzzleFade = 1.f - MuzzleAlpha;
		const double Size = MuzzleDiameter * (0.4 + 0.6 * MuzzleFade) * DiameterScale;
		MuzzleFlash->SetRelativeScale3D(FVector(Size));
		SetMIDColor(MuzzleMID, HotColor, MuzzleIntensity * MuzzleFade * MuzzleFade, /*bGlowScalar=*/true);

		if (MuzzleAlpha >= 1.f)
		{
			MuzzleFlash->SetVisibility(false);
			bMuzzleVisible = false;
		}
	}

	// The impact beat used to be here: an expanding sphere at the hit point. Deleted, spec v4 §4.
}

void ATraceTracer::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	Age += DeltaSeconds;
	ApplyFade(Age / TracerLifeSeconds);
}

// -------------------------------------------------------------------------------------------
// Trace.TestBeam — look at the effect without having to be shooting
//
// Worth its thirty lines. A beam fired in first person runs almost straight away from the camera,
// so a screenshot taken mid-burst shows it nearly edge on and proves very little about whether the
// geometry, the material or the fade are right. This spawns beams ACROSS the view, at a known
// distance, on a timer, so an offscreen automated run can capture the effect square-on. It is also
// the fastest way to re-tune the look without launching a match.
// -------------------------------------------------------------------------------------------
#if !UE_BUILD_SHIPPING
namespace
{
	FTSTicker::FDelegateHandle GTestBeamTicker;
	float GTestBeamRemaining = 0.f;
	float GTestBeamAccumulator = 0.f;

	/** Spawns one broadside beam and one down-the-barrel beam in front of the local camera. */
	void SpawnTestBeams(UWorld* World, const FVector& ViewLocation, const FRotator& ViewRotation)
	{
		const FRotationMatrix Axes(ViewRotation);
		const FVector Forward = Axes.GetScaledAxis(EAxis::X);
		const FVector Right = Axes.GetScaledAxis(EAxis::Y);
		const FVector Up = Axes.GetScaledAxis(EAxis::Z);

		// Broadside: crosses the whole field of view 600 uu out, so nothing about it is foreshortened.
		const FVector Centre = ViewLocation + Forward * 600.0 + Up * -40.0;
		const FVector BroadsideA = Centre - Right * 700.0;
		const FVector BroadsideB = Centre + Right * 700.0;
		ATraceTracer::Spawn(World, BroadsideA, BroadsideB, FLinearColor(0.05f, 0.75f, 1.00f, 1.f), /*bImpacted=*/true);

		// Down the barrel: the real first-person case, including the viewmodel offset.
		ATraceTracer::Spawn(World, ViewLocation + Forward * 22.0, ViewLocation + Forward * 1400.0,
			FLinearColor(1.00f, 0.42f, 0.05f, 1.f), /*bImpacted=*/true);
	}

	void ArmTestBeam(float DurationSeconds)
	{
		GTestBeamRemaining = FMath::Clamp(DurationSeconds, 0.5f, 120.f);
		GTestBeamAccumulator = 0.f;

		if (GTestBeamTicker.IsValid())
		{
			return; // already running; the line above just extended it
		}

		UE_LOG(LogTraceGame, Display, TEXT("TESTBEAM: spawning railgun beams for %.1fs."), GTestBeamRemaining);

		GTestBeamTicker = FTSTicker::GetCoreTicker().AddTicker(FTickerDelegate::CreateLambda(
			[](float Delta) -> bool
			{
				GTestBeamRemaining -= Delta;
				if (GTestBeamRemaining <= 0.f)
				{
					UE_LOG(LogTraceGame, Display, TEXT("TESTBEAM: done."));
					GTestBeamTicker.Reset();
					return false;
				}

				GTestBeamAccumulator += Delta;
				if (GTestBeamAccumulator < 0.2f)
				{
					return true;
				}
				GTestBeamAccumulator = 0.f;

				if (GEngine == nullptr)
				{
					return true;
				}
				for (const FWorldContext& Context : GEngine->GetWorldContexts())
				{
					UWorld* World = Context.World();
					if (World == nullptr || World->GetNetMode() == NM_DedicatedServer)
					{
						continue;
					}
					FVector ViewLocation = FVector::ZeroVector;
					FRotator ViewRotation = FRotator::ZeroRotator;
					if (!GetLocalView(World, ViewLocation, ViewRotation))
					{
						UE_LOG(LogTraceGame, Display, TEXT("TESTBEAM: no local view in world %s"), *GetNameSafe(World));
						continue;
					}
					SpawnTestBeams(World, ViewLocation, ViewRotation);
					UE_LOG(LogTraceGame, Display, TEXT("TESTBEAM: spawned at view %s"), *ViewLocation.ToCompactString());
				}
				return true;
			}), 0.f);
	}
} // namespace

static FAutoConsoleCommand GTraceTestBeamCmd(
	TEXT("Trace.TestBeam"),
	TEXT("Trace.TestBeam [seconds] — spawn railgun beams in front of the local camera so the effect can be inspected."),
	FConsoleCommandWithArgsDelegate::CreateStatic([](const TArray<FString>& Args)
	{
		ArmTestBeam((Args.Num() > 0) ? FCString::Atof(*Args[0]) : 10.f);
	}));
#endif // !UE_BUILD_SHIPPING
