#pragma once

#include "CoreMinimal.h"
#include "Containers/ArrayView.h"
#include "UObject/Object.h"
#include "TraceFxShapes.generated.h"

class UMaterialInstanceDynamic;
class UMaterialInterface;
class UMeshComponent;
class UPrimitiveComponent;
class USceneComponent;
class UStaticMesh;
class UStaticMeshComponent;

/**
 * How a piece of FX geometry is shaded. SPEC v32 §1: "a helper that makes a translucent, unlit,
 * additive MID at a given colour and opacity, with the same fallback discipline ATraceTracer uses
 * for its sheath."
 *
 * The value handed BACK by MakeGlowMID is the blend that was actually achieved, not the one that
 * was asked for, because these assets can legitimately be absent (M_TraceNeon is generated by
 * Scripts/generate_content.py into a gitignored content path) and an effect that silently drew
 * itself in the wrong blend mode is a bug nobody can see in a log. Every caller stores the answer
 * and every probe prints it.
 */
enum class ETraceFxBlend : uint8
{
	/** Nothing resolved. The caller must hide its component: an untextured 100 uu default cylinder
	  * is far worse than no effect at all. */
	None = 0,

	/**
	 * /Game/Generated/Materials/M_TraceNeon — unlit, OPAQUE, EmissiveColor = Color * Glow.
	 * "Color" is a plain 0..1 hue and "Glow" is the multiplier that pushes it past the arena's
	 * bloom threshold. This is the project's own material and the only one that can be pushed far
	 * past white, so it is what every hot core is made of.
	 */
	Emissive,

	/**
	 * /Engine/EngineMaterials/EmissiveMeshMaterial — unlit and BLEND_Additive.
	 * Additive geometry writes no depth, so a fat sleeve cannot hide the thin core inside it. It has
	 * no Glow scalar, so intensity has to ride in the colour and is therefore clamped at 1.0.
	 */
	Additive,

	/**
	 * WHAT THE FX DOC ASKS FOR — "double-sided, ~55% opacity" — AND WHAT IT RESOLVES TO TODAY.
	 *
	 * This project has no translucent parent material. M_TraceNeon and M_TraceSurface are both
	 * BLEND_OPAQUE by deliberate choice (see Scripts/generate_content.py: "neon geometry has to
	 * write depth so it occludes and sorts like solid matter"), and a UMaterialInstanceDynamic
	 * CANNOT change its parent's blend mode — blend mode is baked into the shader permutation.
	 *
	 * So Translucent resolves to Additive, with the requested opacity carried as a weight on the
	 * additive colour. That is a faithful stand-in rather than a fudge: the two properties the doc
	 * actually wants from "translucent, double-sided" are (a) you can see the beam core through the
	 * sleeve and (b) the sleeve does not occlude from any angle, and additive gives both for free
	 * by writing no depth at all. What it does NOT give is darkening — an additive sleeve can only
	 * brighten what is behind it — which on a self-luminous energy weapon is the right sign anyway.
	 *
	 * If a translucent parent is ever generated, point ResolveBlend() at it and this enum value
	 * stops being a synonym. Callers already store and print the achieved blend, so the day that
	 * happens is a day the logs report differently rather than a day something silently changes.
	 */
	Translucent,

	/** /Engine/BasicShapes/BasicShapeMaterial — LIT, "Color" only, no emissive. The last resort when
	  * M_TraceNeon has not been generated: the shape keeps its hue and stops glowing. */
	Fallback
};

/**
 * SPEC v32 §1 — THE SHARED FX SHAPE LIBRARY.
 *
 * Every piece of geometry in Art/Pack/docs/unreal-fx_README.md is built out of engine primitives
 * and dynamic material instances, because build contract 2 says this project cannot author .uasset
 * VFX and ATraceTracer already solved the same problem the same way. This class is that solution
 * factored out so §2's beam, §3's pickup halo and thrown trail and §4's stab streak are all made of
 * the same parts, converted with the same one constant, and degrade the same way.
 *
 * --- WHY IT IS A UOBJECT WHEN EVERY ENTRY POINT IS STATIC ------------------------------------
 *
 * ConstructorHelpers::FObjectFinder asserts outside a UObject constructor, and it is the ONLY thing
 * that leaves a cook reference: a bare runtime LoadObject resolves to null in a packaged build,
 * which is a trap ATraceCore's comments record having fallen into. So the assets are found in this
 * class's constructor and held on its CDO as hard UPROPERTYs, and the static accessors just read
 * GetDefault<UTraceFxShapes>(). Nothing is ever instantiated, nothing has state, and callers never
 * see the CDO.
 *
 * --- THE ROUND PRIMITIVE, AND WHY THE HEXAGON IS NOT WORTH A PASS -----------------------------
 *
 * The FX doc says "6-sided" of both the beam cylinder and the muzzle cone. That describes the
 * ORIGINAL PREVIEW VIEWER's geometry, not a requirement: /Engine/BasicShapes/Cylinder and Cone are
 * round. At a 3.0 uu radius, seen from more than a few centimetres, a hexagon and a circle differ
 * by well under a pixel — and writing a runtime mesh builder to win that is a pass spent on
 * something no player can see. ADOPTED DELIBERATELY: round engine primitives, stated here so the
 * deviation is a decision on the record rather than an oversight.
 *
 * --- UNITS. GET THIS WRONG AND EVERYTHING IS 100x OFF -----------------------------------------
 *
 * THE FX DOC IS IN METRES. UNREAL IS IN CENTIMETRES. r 0.030 m = 3.0 uu. And /Engine/BasicShapes
 * primitives are 100 uu ACROSS at scale 1 — so a 3.0 uu RADIUS cylinder is SetWorldScale3D 0.06,
 * not 3.0 and not 0.03. Both halves of that live in RadiusUUToShapeScale below, which is the one
 * named constant §1 asks for; nothing in this module may divide by 100 by hand.
 */
UCLASS()
class TRACE_API UTraceFxShapes : public UObject
{
	GENERATED_BODY()

public:
	UTraceFxShapes();

	// =============================================================================================
	// UNITS — one conversion, used everywhere
	// =============================================================================================

	/** /Engine/BasicShapes primitives are 100 uu across AND 100 uu tall at scale 1. */
	static constexpr float BasicShapeExtentUU = 100.0f;

	/** The FX doc is in metres; Unreal is in centimetres. */
	static constexpr float MetresToUU = 100.0f;

	/**
	 * *** THE CONSTANT. *** Multiply a RADIUS in uu by this to get the X/Y scale of a BasicShape
	 * cylinder, cone or sphere. The 2 is because the primitives are specified by DIAMETER: a 3.0 uu
	 * radius is a 6.0 uu wide shape, which is 0.06 of a 100 uu one.
	 */
	static constexpr float RadiusUUToShapeScale = 2.0f / BasicShapeExtentUU;

	/** Multiply a LENGTH in uu by this to get the Z scale of a BasicShape cylinder or cone. */
	static constexpr float LengthUUToShapeScale = 1.0f / BasicShapeExtentUU;

	static constexpr float ShapeScaleForRadiusUU(float RadiusUU) { return RadiusUU * RadiusUUToShapeScale; }
	static constexpr float ShapeScaleForLengthUU(float LengthUU) { return LengthUU * LengthUUToShapeScale; }

	/** The FX doc's own units, straight through: ShapeScaleForRadiusMetres(0.030f) == 0.06f. */
	static constexpr float ShapeScaleForRadiusMetres(float RadiusMetres) { return ShapeScaleForRadiusUU(RadiusMetres * MetresToUU); }
	static constexpr float ShapeScaleForLengthMetres(float LengthMetres) { return ShapeScaleForLengthUU(LengthMetres * MetresToUU); }

	/**
	 * The inverses, FOR PROBES. A verifier that re-derives the radius it expects is only checking
	 * its own arithmetic; reading the number back off the live component's scale is a measurement of
	 * the thing on screen. Every FX probe in this module reports through these.
	 */
	static constexpr float RadiusUUFromShapeScale(float Scale) { return Scale / RadiusUUToShapeScale; }
	static constexpr float LengthUUFromShapeScale(float Scale) { return Scale / LengthUUToShapeScale; }

	// =============================================================================================
	// CACHED ENGINE PRIMITIVES
	// =============================================================================================

	/** /Engine/BasicShapes/Cylinder — 100 uu across, 100 uu tall, centred on its own origin. */
	static UStaticMesh* GetCylinder();

	/** /Engine/BasicShapes/Cone — 100 uu across at the base, 100 uu tall, apex up local +Z. */
	static UStaticMesh* GetCone();

	/** /Engine/BasicShapes/Plane — 100 x 100 uu in local XY, facing +Z. */
	static UStaticMesh* GetPlane();

	/** /Engine/BasicShapes/Sphere — 100 uu across. */
	static UStaticMesh* GetSphere();

	/**
	 * The FX doc's "icosahedron halo". THE ENGINE SHIPS NO ICOSPHERE — /Engine/BasicShapes holds
	 * Cone, Cube, Cylinder, Plane and Sphere and nothing else — so this tries the two paths an
	 * icosphere would live at, once and quietly, and otherwise returns GetSphere(). SPEC v32 §1
	 * names that as the documented degradation. The outcome is logged once at Display so "we got the
	 * sphere" is a fact in the log rather than an assumption in a comment.
	 */
	static UStaticMesh* GetIcosphere();

	/** True when GetIcosphere() had to fall back to the round engine sphere. For probes. */
	static bool IsIcosphereDegraded();

	// =============================================================================================
	// MATERIALS
	// =============================================================================================

	/** The parent material for a blend, or null when that asset did not resolve. */
	static UMaterialInterface* GetMaterial(ETraceFxBlend Blend);

	/**
	 * Creates a dynamic material instance on @p Component's element @p ElementIndex.
	 *
	 * @param Preferred     what the effect wants.
	 * @param OutAchieved   the blend ACTUALLY used, which may be a degradation of @p Preferred:
	 *                        Translucent -> Additive   (no translucent parent exists; see the enum)
	 *                        Additive    -> Emissive   (engine material missing)
	 *                        Emissive    -> Fallback   (M_TraceNeon not generated)
	 *                        anything    -> None       (nothing at all; hide the component)
	 *                      SetGlow MUST be given this value and not @p Preferred.
	 * @return              the instance, or null if nothing resolved.
	 *
	 * The MID is RETURNED rather than written through a pointer-to-pointer so that callers can
	 * assign it straight into a TObjectPtr UPROPERTY, which is where a MID has to live to survive
	 * a garbage collection. An `UMaterialInstanceDynamic*&` out-parameter cannot bind to one.
	 *
	 * The degradation is logged ONCE per blend per run, never per frame — this is called up to
	 * eighty times a second in a full match and a per-shot warning would be its own outage.
	 */
	static UMaterialInstanceDynamic* MakeGlowMID(UMeshComponent* Component, int32 ElementIndex,
		ETraceFxBlend Preferred, ETraceFxBlend& OutAchieved);

	/**
	 * Pushes colour, brightness and opacity into a MID made by MakeGlowMID.
	 *
	 * @param Blend    MUST be the value MakeGlowMID returned, not the one that was requested. The
	 *                 two materials take intensity by completely different routes and writing a
	 *                 parameter a material does not have is a silent no-op.
	 * @param Color    a plain 0..1 hue. Brightness NEVER rides here on the Emissive path: a material
	 *                 instance clamps vector parameters to [0,1], so Color * 6 silently becomes flat
	 *                 white at intensity 1 and the piece renders as dull matte with no bloom. That
	 *                 failure looks exactly like "the effect is not rendering" and has cost this
	 *                 project a debugging session already.
	 * @param Opacity  0..1. WHAT IT MEANS PER BLEND, because there is only one honest answer for an
	 *                 opaque material: on Additive/Translucent it weights the additive colour, which
	 *                 IS that blend's opacity; on Emissive and Fallback, which write depth and have
	 *                 no alpha, it multiplies brightness instead, so a piece "fades" by dimming.
	 */
	static void SetGlow(UMaterialInstanceDynamic* MID, ETraceFxBlend Blend,
		const FLinearColor& Color, float Intensity, float Opacity = 1.0f);

	/** "Emissive" / "Additive" / ... — for log lines and probes. Never null. */
	static const TCHAR* BlendName(ETraceFxBlend Blend);

	// =============================================================================================
	// COMPONENT SETUP
	// =============================================================================================

	/**
	 * The shared "this is decoration" pass: no collision, no overlaps, no shadow, no decals, not an
	 * occluder, movable. Getting any of those wrong on a thing that spawns eighty times a second is
	 * a performance bug, and a COLLIDING piece of FX would break hitscan outright — which is the one
	 * failure SPEC v32 §1 says a verifier will check for.
	 */
	static void ConfigureFxComponent(UPrimitiveComponent* Component);

	// =============================================================================================
	// GEOMETRY HELPERS
	// =============================================================================================

	/**
	 * Lays a BasicShape cylinder along the owner's LOCAL +Z, from StartZ to EndZ, at RadiusUU.
	 *
	 * Local rather than world because that is how the beam is built: the tracer actor is rotated so
	 * +Z runs down the shot and every piece is then placed by its distance along the beam. Callers
	 * with two world points want StretchBetween instead.
	 */
	static void StretchAlongLocalZ(USceneComponent* Piece, double StartZ, double EndZ, float RadiusUU);

	/** The same, from two world points: positions and orients @p Piece so its local +Z runs From->To. */
	static void StretchBetween(USceneComponent* Piece, const FVector& From, const FVector& To, float RadiusUU);

	/**
	 * A TAPER, which one mesh cannot do.
	 *
	 * *** WHICH OF THE TWO OPTIONS THIS IS, AND WHY. *** SPEC v32 §1 offers "two or three stacked
	 * segments with decreasing scale, or a cone-plus-cylinder". This is STACKED SEGMENTS, because
	 * the FX doc's tapers all run between two NON-ZERO radii — 0.030 -> 0.013 for the beam,
	 * 0.055 -> 0.012 for the thrown trail — and a cone tapers to a point. Getting a frustum out of
	 * /Engine/BasicShapes/Cone means clipping it, which needs a mesh builder; getting one out of
	 * three cylinders costs two extra components and no code.
	 *
	 * The visible cost is the step between segments. For the pistol beam that is 3.0 -> 1.3 uu over
	 * three segments: steps of 0.57 uu, i.e. half a centimetre, on geometry the player sees for
	 * 0.85 s at a minimum of eighty centimetres. It is not resolvable, and the alternative was a
	 * pass spent writing a runtime frustum builder.
	 *
	 * Each segment is a plain cylinder at the radius of its own MID-POINT along the taper, so the
	 * stack straddles the ideal cone rather than sitting entirely inside or outside it.
	 *
	 * @param Segments          any number of components; unused entries beyond what is supplied are
	 *                          simply not written, and null entries are skipped.
	 * @param OutSegmentRadiiUU optional, Segments.Num() floats, the radius each segment was given.
	 *                          For probes: it is the number a verifier can compare against the doc.
	 * @return                  how many segments were actually placed.
	 */
	static int32 TaperAlongLocalZ(TArrayView<UStaticMeshComponent* const> Segments,
		double StartZ, double EndZ, float StartRadiusUU, float EndRadiusUU,
		float* OutSegmentRadiiUU = nullptr);

	/** The same taper between two world points. */
	static int32 TaperBetween(TArrayView<UStaticMeshComponent* const> Segments,
		const FVector& From, const FVector& To, float StartRadiusUU, float EndRadiusUU,
		float* OutSegmentRadiiUU = nullptr);

	/** The ideal taper radius at normalised distance @p Alpha (0 = start, 1 = end). */
	static constexpr float TaperRadiusAt(float StartRadiusUU, float EndRadiusUU, float Alpha)
	{
		return StartRadiusUU + (EndRadiusUU - StartRadiusUU) * Alpha;
	}

	/** The radius TaperAlongLocalZ gives segment @p Index of @p Count — its mid-point radius. */
	static float TaperSegmentRadiusUU(float StartRadiusUU, float EndRadiusUU, int32 Index, int32 Count);

	/**
	 * Places a BasicShape CONE with its base at local Z = @p BaseZ and its apex @p HeightUU further
	 * up local +Z, i.e. pointing down the beam. The engine cone is centred on its own origin, so
	 * this is the offset callers otherwise get wrong by half a cone.
	 */
	static void PlaceConeAlongLocalZ(USceneComponent* Piece, double BaseZ, float RadiusUU, float HeightUU);

	/**
	 * Sizes a BasicShape PLANE to @p WidthUU x @p HeightUU in its own local XY. (§4's stab streak.)
	 * Z scale is left at 1: a plane has no thickness and scaling it in Z does nothing but confuse
	 * anybody reading the transform back.
	 */
	static void SizePlane(USceneComponent* Piece, float WidthUU, float HeightUU);

	/**
	 * The MEASURED extent of each resolved primitive, logged once at Display.
	 *
	 * The 100 uu assumption above is load-bearing for every number in the FX doc, and it is an
	 * assumption about assets shipped by somebody else. This prints what the meshes actually are, so
	 * the day an engine upgrade changes one, the log says so instead of the effects quietly being
	 * the wrong size. Called automatically the first time any primitive is requested; safe to call
	 * again, it only prints once.
	 */
	static void LogPrimitiveGeometryOnce();

private:
	/** Resolves @p Preferred down to a blend whose parent material actually exists. */
	static ETraceFxBlend ResolveBlend(ETraceFxBlend Preferred);

	UPROPERTY()
	TObjectPtr<UStaticMesh> CylinderMesh;

	UPROPERTY()
	TObjectPtr<UStaticMesh> ConeMesh;

	UPROPERTY()
	TObjectPtr<UStaticMesh> PlaneMesh;

	UPROPERTY()
	TObjectPtr<UStaticMesh> SphereMesh;

	UPROPERTY()
	TObjectPtr<UMaterialInterface> NeonMaterial;

	UPROPERTY()
	TObjectPtr<UMaterialInterface> AdditiveMaterial;

	UPROPERTY()
	TObjectPtr<UMaterialInterface> FallbackMaterial;
};
