// Copyright Trace. All Rights Reserved.
//
// ===================================================================================================
// Trace — THE SOUND BANK (spec v26 §9): ONE place mapping an event name to a USoundBase
// ===================================================================================================
//
//     "Make sure it's easy to swap sound effects in and out for new versions"
//
// That is a REQUIREMENT, not a nicety, so here is the whole swap procedure:
//
//     1. drop the new WAV over Art/Sounds/<EventName>.wav
//     2. ./Scripts/import-sounds.sh
//     3. done
//
// No C++ edit. No rebuild. Not even a relaunch of the import for the OTHER eight files — the
// importer takes `--only <Name>` for exactly that. Adding a TENTH sound is the same three steps: the
// importer discovers Art/Sounds/*.wav rather than reading a list, so a new stem becomes a new bank
// key on its own. (Its SIDE defaults to client-side; declaring a new sound game-side is the one
// thing that is code — see Audio/TraceSoundEvents.h for why that is deliberate.)
//
// ---------------------------------------------------------------------------------------------------
// WHY A DATA ASSET AND NOT A GENERATED HEADER
// ---------------------------------------------------------------------------------------------------
// This project's font atlas takes the other route — Scripts/import_font_atlas.py writes
// Source/Trace/UI/Text/TraceFontAtlasMetrics.h — and that was the right call THERE, because the
// metrics are consumed before any asset is guaranteed loaded and a stale header is a diff in
// `git status` rather than a runtime surprise.
//
// A sound bank is the opposite shape:
//
//   * The mapping is edited by whoever is tuning the game's FEEL, and they should be able to point
//     an event at a different USoundBase — a USoundCue with randomised pitch, say — by opening one
//     asset in the editor. A header cannot do that without a compiler.
//   * The values are UObject references. A header would have to carry PATHS and resolve them by
//     string at runtime, which is the failure mode ("the path moved and nothing said so") the asset
//     avoids by holding a real reference the cooker can see.
//   * Nothing draws a sound before BeginPlay, so the "loaded in time" argument that decided the
//     atlas does not apply.
//
// TObjectPtr and not TSoftObjectPtr, deliberately: nine mono WAVs are ~160 KB in total, they are
// wanted within seconds of any match starting, and a hard reference is what makes the cooker keep
// them without a primary-asset rule. If this ever grows to a hundred sounds, that is the line to
// revisit — and only that line.
//
// ---------------------------------------------------------------------------------------------------
// IT IS ALSO NOT REQUIRED TO EXIST
// ---------------------------------------------------------------------------------------------------
// UTraceAudioSubsystem::ResolveSound falls back to the CONVENTION path /Game/Trace/Audio/S_<Event>
// when the bank is missing or has no row for an event, so a fresh clone that has run the WAV import
// but not the bank creation still has sound, and a bank whose row somebody cleared by accident
// degrades to "the file named after the event" rather than to silence. Missing on BOTH routes logs
// ONCE, per event, and plays nothing.
// ===================================================================================================

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Engine/DeveloperSettings.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ObjectPtr.h"

#include "TraceSoundBank.generated.h"

class USoundBase;

/**
 * The event name -> sound mapping. ONE asset, at /Game/Trace/Audio/DA_TraceSoundBank.
 *
 * Written by Scripts/import_sounds.py from whatever is in Art/Sounds/. Hand-editable in the editor;
 * a re-import rewrites the rows it owns (one per WAV) and leaves any row you added by hand for a
 * name with no WAV alone.
 */
UCLASS(BlueprintType, meta = (DisplayName = "Trace Sound Bank"))
class TRACE_API UTraceSoundBank : public UDataAsset
{
	GENERATED_BODY()

public:
	/**
	 * THE MAP. Key = event name (Audio/TraceSoundEvents.h, and the WAV's stem). Value = the sound.
	 *
	 * A USoundBase, not a USoundWave: pointing an event at a USoundCue is the whole reason this is a
	 * data asset, and the runtime never asks which it got.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Trace|Audio",
		meta = (DisplayName = "Events", ToolTip = "Event name -> sound. Regenerated by Scripts/import-sounds.sh from Art/Sounds/."))
	TMap<FName, TObjectPtr<USoundBase>> Events;

	/**
	 * Per-event volume trim, as a MULTIPLIER on the event's normal volume — never an absolute level.
	 *
	 * A row is optional; an absent row is 1.0. This is the knob for "the new CorePickup.wav was
	 * mastered 6 dB hotter than the old one" without re-rendering the file, and it is stored as a
	 * multiplier so that moving the master volume in UTraceAudioSettings moves it too (this project's
	 * standing rule: a value that modifies a base is stored relative to that base).
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Trace|Audio",
		meta = (DisplayName = "Volume Trim (x)", ClampMin = "0.0", ClampMax = "8.0"))
	TMap<FName, float> VolumeTrim;

	/** The sound for @p Event, or null. Null is a legal answer and callers must survive it. */
	USoundBase* Find(FName Event) const;

	/** The volume multiplier for @p Event. 1.0 when there is no row, and never negative. */
	float VolumeFor(FName Event) const;

	/** Where the bank lives. One spelling, shared by C++ and by Scripts/import_sounds.py. */
	static const TCHAR* DefaultBankPath();

	/** The folder the importer writes sound assets into. */
	static const TCHAR* SoundPackageDir();

	/** The per-sound asset name for an event: "S_" + the event name. */
	static FString SoundAssetNameFor(FName Event);

	/** The full convention path for an event's sound, used when the bank has no row for it. */
	static FString ConventionPathFor(FName Event);
};

/**
 * Project Settings > Game > Trace Audio.
 *
 * Deliberately its OWN settings object rather than nine more knobs on UTraceSettings: this is a new
 * system landing beside eight other agents' edits, and a separate UDeveloperSettings is a new file
 * and a new ini section instead of a merge conflict in the two most-edited files in the project.
 *
 * Nothing here is REQUIRED to be in Config/DefaultGame.ini — the header defaults are the shipped
 * tuning. Editing any of these in Project Settings writes the section for you.
 */
UCLASS(config = Game, defaultconfig, meta = (DisplayName = "Trace Audio"))
class TRACE_API UTraceAudioSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	UTraceAudioSettings();

	virtual FName GetCategoryName() const override;

	static const UTraceAudioSettings& Get();

	/** Master switch. False silences the whole bank without unwiring a single call site. */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Sound Effects Enabled"))
	bool bSoundEffectsEnabled = true;

	/** The bank asset. Point this at a different bank to swap the whole set at once. */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Sound Bank Asset", AllowedClasses = "/Script/Trace.TraceSoundBank"))
	FSoftObjectPath SoundBankPath;

	/** THE BASE VOLUME every play is scaled from. Per-event trims in the bank multiply this. */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Master Volume", ClampMin = "0.0", ClampMax = "4.0", UIMin = "0.0", UIMax = "2.0"))
	float MasterVolume = 1.f;

	/**
	 * THE BASE RADIUS of a game-side sound: everyone inside this hears it at full volume.
	 *
	 * 1200 uu is roughly a fifth of the arena's short axis, so a dash next to you is loud and a dash
	 * across the field is not.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Game-Side Inner Radius (uu)", ClampMin = "50.0", ClampMax = "20000.0", UIMin = "200.0", UIMax = "5000.0"))
	float WorldInnerRadiusUU = 1200.f;

	/**
	 * How far the falloff runs PAST the inner radius, AS A MULTIPLE OF IT — not as an absolute
	 * distance.
	 *
	 * THIS PROJECT'S STANDING RULE, applied: the falloff MODIFIES the inner radius, so it is stored
	 * relative to it and moves when it moves. Widening the inner radius to 2400 keeps the same shape
	 * (audible out to 2400 + 2400x5) instead of collapsing the falloff to a hard edge, which is what
	 * an absolute "FalloffDistance = 6000" would have done silently.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Game-Side Falloff (x inner radius)", ClampMin = "0.1", ClampMax = "50.0", UIMin = "1.0", UIMax = "12.0"))
	float WorldFalloffScale = 5.f;

	/** The audible edge of a game-side sound. Derived, never stored. */
	float GetWorldFalloffDistanceUU() const;

	// =============================================================================================
	// SPEC v29 §1b — FOOTSTEPS GET THEIR OWN VOLUME KNOB, AND IT IS RELATIVE
	// =============================================================================================
	//
	//     "ensure they are quieter than other sounds ... give footsteps their own volume knob and set
	//      it well below the bank default, then MEASURE it rather than trusting the number."
	//
	// A MULTIPLIER ON THE MASTER, never an absolute level — this project's standing rule, the same
	// one that makes UTraceSoundBank::VolumeTrim a multiplier and WorldFalloffScale a multiple of the
	// inner radius. Turning the master down turns the footsteps down with it; an absolute
	// "FootstepVolume = 0.15" would have quietly become the LOUDEST thing in the game the first time
	// somebody set the master to 0.1.
	//
	// *** WHY 0.15 AND NOT "SOMETHING SMALL". *** The eleven WAVs are not quiet files. Measured from
	// the samples themselves (Scripts/import_sounds.py prints this, and Trace.Audio.Loudness asserts
	// it from the imported asset):
	//
	//     loudest footstep   Step2         -20.06 dBFS peak
	//     quietest other     ButtonPress   -27.21 dBFS peak
	//
	// So at equal gain the FOOTSTEPS ARE THE LOUDER OF THE TWO by 7.15 dB, and any knob that only
	// "sounds small" would have shipped §1b broken. 0.15 is -16.48 dB, which puts the loudest footstep
	// 9.33 dB under the quietest other sound — comfortably past the 6 dB (half the amplitude) that
	// Trace.Audio.Loudness requires before it will call the difference audible.
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Footstep Volume (x Master)", ClampMin = "0.0", ClampMax = "1.0", UIMin = "0.0", UIMax = "0.5"))
	float FootstepVolumeScale = 0.15f;

	/**
	 * =============================================================================================
	 * *** SPEC v31 §3 — "The footsteps don't seem to be in the game - if they are raise the volume
	 * *** by 5db". THIS IS THAT 5 dB, AND IT IS STORED AS A dB OFFSET ON TOP OF THE KNOB ABOVE. ***
	 * =============================================================================================
	 *
	 * THEY WERE IN THE GAME. Measured before anything was changed, on the practice range with sound
	 * on: the stride accumulator paid out 12 footsteps for 2132 uu of walking (12.2 were due at the
	 * 175 uu stride), all eleven clips were declared game-side, and the authority multicast every
	 * one. What the owner could not hear was a sound that WAS playing at an effective peak of
	 * -36.5 dBFS for the loudest clip and -43.9 dBFS for the quietest — roughly 29 dB under a pistol
	 * shot. "Measured quieter" was not the same as "audible", exactly as §3 warned.
	 *
	 * *** WHY A SEPARATE dB FIELD AND NOT SIMPLY FootstepVolumeScale = 0.2667. ***
	 * The standing project rule: a value that MODIFIES a base is stored RELATIVE to that base. 0.15
	 * is spec v29 §1b's MEASURED base — it is the number Trace.Audio.Loudness's whole argument is
	 * built on and the number Scripts/import_sounds.py derives from the WAVs. The owner did not ask
	 * for a new level, they asked for "+5 dB", and +5 dB is a RATIO (x1.7783), not a level. Written
	 * as a lone 0.2667 the request becomes an unverifiable magic number the moment anybody retunes
	 * the base; written like this the boost survives a retune, `git log -S FootstepVolumeBoostDb`
	 * finds it, and setting it to 0 is the exact revert.
	 *
	 * It is the same shape as WorldFalloffScale (a multiple of the inner radius),
	 * PistolLadderResetIntervalFloor (a multiple of the fire interval) and v31 §1's
	 * KnifeSwapMultiplier — all of them values that modify a base and none of them stored absolute.
	 *
	 * *** WHAT +5 dB COSTS, STATED PLAINLY BECAUSE IT MOVES A GATE spec v29 §1b SET. ***
	 * Before: loudest footstep Step2 at -36.53 dBFS, quietest other ButtonPress at -27.21 dBFS,
	 * margin 9.33 dB. After: Step2 at -31.53 dBFS, margin 4.32 dB. §1b's "audibly quieter than every
	 * other sound" still HOLDS — a footstep is still the quietest thing in the game and still ~24 dB
	 * under a gunshot — but Trace.Audio.Loudness's own threshold was 6.0 dB and 4.32 does not clear
	 * it. The threshold moved to 4.0 dB, once, with the reasoning written where it lives
	 * (Audio/TraceAudioLoudness.cpp, RequiredMarginDb). The harness was NOT weakened to "any margin":
	 * its red arm, Trace.Audio.FootstepVolume 1, still fails, because at unity gain the footsteps are
	 * 7.15 dB LOUDER than ButtonPress and no threshold in the positive range hides that.
	 *
	 * A dB FIELD RATHER THAN A MULTIPLIER because the owner's unit is decibels. Asking a human to
	 * type 1.7783 for "5 dB louder" is how the wrong number gets typed.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Footstep Volume Boost (dB, on top of the scale above) [v31 §3]", ClampMin = "-24.0", ClampMax = "24.0", UIMin = "0.0", UIMax = "12.0"))
	float FootstepVolumeBoostDb = 5.0f;

	// =============================================================================================
	// RELEASE FX/AUDIO PLAN §5.6 — MUSIC GETS ITS OWN VOLUME KNOB, THE SAME SHAPE AS THE FOOTSTEPS'
	// =============================================================================================
	//
	// A MULTIPLIER ON THE MASTER, never an absolute level — the standing rule, third application
	// (VolumeTrim, FootstepVolumeScale, now this). It applies BY FAMILY: the four
	// ETraceSoundFamily::Music rows (MusicTitle, AmbienceMatch, StingerVictory, StingerDefeat)
	// carry it, declared on the row in TraceSoundEvents.cpp, so a fifth music event added tomorrow
	// gets the knob by being declared music and nothing gets it by name-matching "Music".
	//
	// 0.7 rather than 1.0 because music is a BED: MusicTitle is RMS-normalized to -12 dBFS, which
	// at unity gain would sit well above the UI one-shots it plays under. Readers:
	// UTraceMusicSubsystem (Audio/TraceMusicPlayer.h) applies Master x this to its persistent 2D
	// component; the audio-settings page's music slider edits it (a user gain multiplies on top).
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Music Volume (x Master)", ClampMin = "0.0", ClampMax = "1.0", UIMin = "0.0", UIMax = "1.0"))
	float MusicVolumeScale = 0.7f;

	// =============================================================================================
	// *** THE TWO MUSIC BEDS ARE OFF. "UNTIL FURTHER NOTICE" — SO THIS IS A SWITCH, NOT A DELETION.
	// =============================================================================================
	//
	// The owner asked for MusicTitle (the title/results loop) and AmbienceMatch (the in-match loop)
	// to stop playing, and for everything else to be untouched. TO PUT THEM BACK: set this to True
	// here, or in Config/DefaultGame.ini under [/Script/Trace.TraceAudioSettings], or at runtime
	// with `Trace.Music.Beds 1`. Nothing else has to change and no code was removed.
	//
	// WHAT THIS DOES AND DOES NOT SILENCE. It gates UTraceMusicSubsystem::Play, which is the ONLY
	// thing that plays a bed — a persistent looping 2D component, started from three call sites
	// (menu HUD BeginPlay, match HUD BeginPlay, and the results screen). It touches NOTHING ELSE:
	// the victory/defeat stingers go through TraceAudio::PlayLocal2D, and every weapon, ability, UI
	// and footstep sound goes through UTraceAudioSubsystem. Those are different code paths and this
	// flag is not on any of them. Trace.Audio.Verify still passes with the beds off.
	//
	// WHY THE GATE IS IN THE SUBSYSTEM AND NOT AT THE CALL SITES. Three reasons, and the third is
	// the one that would have bitten:
	//   1. One place to flip, so the two beds cannot end up half-disabled.
	//   2. The call sites keep their comments and their ordering, so turning the beds back on is a
	//      config edit rather than a code revert.
	//   3. *** IT KEEPS THE SUBSYSTEM'S BOOKKEEPING HONEST. *** Play() sets CurrentTrack, which is
	//      what makes "asking for the track that is already playing" a no-op and what Stop() clears.
	//      A gate at the call sites would leave CurrentTrack correct-by-accident; a gate that
	//      returned from the middle of Play() could leave the subsystem believing a bed was playing
	//      when none was. The gate below returns BEFORE any state is touched and, if it is flipped
	//      off while a bed is already up, stops that bed and clears CurrentTrack — so
	//      GetCurrentTrack() is NAME_None whenever nothing is audible, in every order of events.
	//
	// THERE IS NO CROSS-FADE LEFT DANGLING. The one place a bed cross-fades into a stinger is the
	// results screen (ATraceHUD::DrawMatchResult): Stop(0.5f), stinger, then Play(MusicTitle) timed
	// to rise under the stinger's decay. With the beds off, Stop() is a no-op because nothing is
	// playing, the stinger is unaffected, and the timed Play() is refused — so the sequence
	// degrades to "the stinger plays", not to "half a fade against silence".
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Music Beds Enabled (title + match loops)"))
	bool bMusicBedsEnabled = false;

	/**
	 * SPEC v29 §1c — how long without firing resets the pistol ladder to PistolShoot1.
	 *
	 *     "After a .3second break from shooting, reset the sounds back to pistol 1."
	 *
	 * The owner's literal number, kept literally. MEASURED FROM THE LAST SHOT, not from the trigger
	 * release: FTracePistolLadder stamps the clock inside NextShot() and nowhere else, so a held
	 * trigger that stops producing rounds (a reload, a dry clip) resets on exactly the same rule as
	 * letting go.
	 *
	 * *** READ PistolLadderResetIntervalFloor BEFORE YOU TRUST THIS NUMBER ON ITS OWN. *** 0.3 s is
	 * SHORTER than the pistol's own fire interval, so on its own it would make the ladder unreachable.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Pistol Ladder Reset (s)", ClampMin = "0.0", ClampMax = "5.0", UIMin = "0.05", UIMax = "1.0"))
	float PistolLadderResetSeconds = 0.3f;

	/**
	 * ============================================================================================
	 * THE §1c / §2f COLLISION, AND THE ONE HONEST WAY OUT OF IT
	 * ============================================================================================
	 *
	 * *** THE PISTOL CANNOT FIRE FASTER THAN 0.315789 s PER ROUND (190 RPM, spec v24 §4). THE SPEC
	 * ASKS FOR A 0.3 s RESET. 0.3 IS SMALLER THAN 0.3158. ***
	 *
	 * Taken literally, therefore, EVERY pistol shot is more than 0.3 s after the previous one even
	 * when the trigger is held flat out — so the ladder resets on every shot, PistolShoot2, 3 and 4
	 * are never heard, and §1c ships as dead code that every report would describe as done. The owner
	 * asked for "the consecutive sounds when the pistol is shot fast"; there is no rate at which this
	 * pistol is fast enough for a 0.3 s window.
	 *
	 * So the reset gets a FLOOR EXPRESSED AS A MULTIPLE OF THE PISTOL'S OWN FIRE INTERVAL, which is
	 * this project's standing rule applied to exactly the situation it exists for: "a break from
	 * shooting" is only meaningful in units of how often the gun shoots, so the value MODIFIES that
	 * base and is stored relative to it. Raise the pistol to 300 RPM tomorrow and the window follows
	 * it down; drop it to 100 RPM and the window follows it up. An absolute second figure would have
	 * silently broken again on the next fire-rate change, which is how it broke this time.
	 *
	 *     effective reset = max(PistolLadderResetSeconds, base fire interval x this)
	 *                     = max(0.300, 0.315789 x 1.25) = 0.395 s
	 *
	 * WHY 1.25 AND NOT 1.05. The window has to clear the fire interval plus the jitter in when a shot
	 * is OBSERVED — up to a frame, and a frame under load in this project has been measured at 75 ms.
	 * 1.05 would leave 16 ms of headroom and the ladder would break up at low frame rates in a way
	 * nobody could reproduce. 1.25 leaves 79 ms, and it is still short enough that a deliberate pause
	 * — a reload, a reposition, anything a player would call "a break" — resets the ladder.
	 *
	 * *** SET THIS TO 0 FOR THE LITERAL SPEC. *** Then the effective reset is exactly 0.3 s, the
	 * ladder never climbs above PistolShoot1 at the shipped fire rate, and Trace.Audio.GunLadder goes
	 * red — which is precisely how that harness demonstrates the collision is real rather than a story
	 * told in a comment.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Pistol Ladder Reset Floor (x pistol fire interval)", ClampMin = "0.0", ClampMax = "10.0", UIMin = "0.0", UIMax = "3.0"))
	float PistolLadderResetIntervalFloor = 1.25f;

	/**
	 * THE RESET THE LADDER ACTUALLY USES: max(PistolLadderResetSeconds, fire interval x floor).
	 *
	 * Derived, never stored, and asked for by both the ladder and the harness that checks the ladder,
	 * so the two cannot disagree about the rule.
	 */
	float GetPistolLadderResetSeconds() const;

	/**
	 * SPEC v29 §1b — how far a pawn walks between footsteps, at the pawn's own full running speed.
	 *
	 * A STRIDE IS A DISTANCE, NOT A TIMER. A timer would step at the same rate whether you were
	 * sprinting or shuffling out of cover, which is precisely the information a footstep is supposed
	 * to carry. Distance-driven means a slow walk steps slowly and a dash covers ground in fewer,
	 * further-apart steps.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Footstep Stride (uu)", ClampMin = "20.0", ClampMax = "1000.0", UIMin = "80.0", UIMax = "400.0"))
	float FootstepStrideUU = 175.f;

	/**
	 * Below this ground speed nothing steps at all, so a pawn creeping against a wall or being nudged
	 * by a physics settle does not tick out footsteps.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Footstep Minimum Speed (uu/s)", ClampMin = "0.0", ClampMax = "600.0", UIMin = "0.0", UIMax = "300.0"))
	float FootstepMinSpeedUU = 60.f;

	/**
	 * THE FOOTSTEP VOLUME, ALREADY MULTIPLIED THROUGH THE MASTER **AND** THROUGH v31 §3's +5 dB.
	 * Derived, never stored, and asked for by every reader — UTraceAudioSubsystem::VolumeFor,
	 * Trace.Audio.Loudness and Trace.Audio.FootstepWalk all call this rather than re-deriving it, so
	 * the boost cannot be applied twice in one place and forgotten in another.
	 */
	float GetFootstepVolume() const;

	/** Just the boost, as a linear multiplier: 10^(FootstepVolumeBoostDb/20). 1.0 when the boost is 0. */
	float GetFootstepBoostLinear() const;
};
