// Copyright Trace. All Rights Reserved.
//
// ===================================================================================================
// Trace — THE SOUND BANK (spec v26 §9): ONE place mapping an event name to a USoundBase
// ===================================================================================================
//
//     "Make sure it's easy to swap sound effects in and out for new versions"
//
// That is a REQUIREMENT, not a nicety, so here is the whole swap procedure:
//
//     1. drop the new WAV over Art/Sounds/<EventName>.wav
//     2. ./Scripts/import-sounds.sh
//     3. done
//
// No C++ edit. No rebuild. Not even a relaunch of the import for the OTHER eight files — the
// importer takes `--only <Name>` for exactly that. Adding a TENTH sound is the same three steps: the
// importer discovers Art/Sounds/*.wav rather than reading a list, so a new stem becomes a new bank
// key on its own. (Its SIDE defaults to client-side; declaring a new sound game-side is the one
// thing that is code — see Audio/TraceSoundEvents.h for why that is deliberate.)
//
// ---------------------------------------------------------------------------------------------------
// WHY A DATA ASSET AND NOT A GENERATED HEADER
// ---------------------------------------------------------------------------------------------------
// This project's font atlas takes the other route — Scripts/import_font_atlas.py writes
// Source/Trace/UI/Text/TraceFontAtlasMetrics.h — and that was the right call THERE, because the
// metrics are consumed before any asset is guaranteed loaded and a stale header is a diff in
// `git status` rather than a runtime surprise.
//
// A sound bank is the opposite shape:
//
//   * The mapping is edited by whoever is tuning the game's FEEL, and they should be able to point
//     an event at a different USoundBase — a USoundCue with randomised pitch, say — by opening one
//     asset in the editor. A header cannot do that without a compiler.
//   * The values are UObject references. A header would have to carry PATHS and resolve them by
//     string at runtime, which is the failure mode ("the path moved and nothing said so") the asset
//     avoids by holding a real reference the cooker can see.
//   * Nothing draws a sound before BeginPlay, so the "loaded in time" argument that decided the
//     atlas does not apply.
//
// TObjectPtr and not TSoftObjectPtr, deliberately: nine mono WAVs are ~160 KB in total, they are
// wanted within seconds of any match starting, and a hard reference is what makes the cooker keep
// them without a primary-asset rule. If this ever grows to a hundred sounds, that is the line to
// revisit — and only that line.
//
// ---------------------------------------------------------------------------------------------------
// IT IS ALSO NOT REQUIRED TO EXIST
// ---------------------------------------------------------------------------------------------------
// UTraceAudioSubsystem::ResolveSound falls back to the CONVENTION path /Game/Trace/Audio/S_<Event>
// when the bank is missing or has no row for an event, so a fresh clone that has run the WAV import
// but not the bank creation still has sound, and a bank whose row somebody cleared by accident
// degrades to "the file named after the event" rather than to silence. Missing on BOTH routes logs
// ONCE, per event, and plays nothing.
// ===================================================================================================

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Engine/DeveloperSettings.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ObjectPtr.h"

#include "TraceSoundBank.generated.h"

class USoundBase;

/**
 * The event name -> sound mapping. ONE asset, at /Game/Trace/Audio/DA_TraceSoundBank.
 *
 * Written by Scripts/import_sounds.py from whatever is in Art/Sounds/. Hand-editable in the editor;
 * a re-import rewrites the rows it owns (one per WAV) and leaves any row you added by hand for a
 * name with no WAV alone.
 */
UCLASS(BlueprintType, meta = (DisplayName = "Trace Sound Bank"))
class TRACE_API UTraceSoundBank : public UDataAsset
{
	GENERATED_BODY()

public:
	/**
	 * THE MAP. Key = event name (Audio/TraceSoundEvents.h, and the WAV's stem). Value = the sound.
	 *
	 * A USoundBase, not a USoundWave: pointing an event at a USoundCue is the whole reason this is a
	 * data asset, and the runtime never asks which it got.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Trace|Audio",
		meta = (DisplayName = "Events", ToolTip = "Event name -> sound. Regenerated by Scripts/import-sounds.sh from Art/Sounds/."))
	TMap<FName, TObjectPtr<USoundBase>> Events;

	/**
	 * Per-event volume trim, as a MULTIPLIER on the event's normal volume — never an absolute level.
	 *
	 * A row is optional; an absent row is 1.0. This is the knob for "the new CorePickup.wav was
	 * mastered 6 dB hotter than the old one" without re-rendering the file, and it is stored as a
	 * multiplier so that moving the master volume in UTraceAudioSettings moves it too (this project's
	 * standing rule: a value that modifies a base is stored relative to that base).
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Trace|Audio",
		meta = (DisplayName = "Volume Trim (x)", ClampMin = "0.0", ClampMax = "8.0"))
	TMap<FName, float> VolumeTrim;

	/** The sound for @p Event, or null. Null is a legal answer and callers must survive it. */
	USoundBase* Find(FName Event) const;

	/** The volume multiplier for @p Event. 1.0 when there is no row, and never negative. */
	float VolumeFor(FName Event) const;

	/** Where the bank lives. One spelling, shared by C++ and by Scripts/import_sounds.py. */
	static const TCHAR* DefaultBankPath();

	/** The folder the importer writes sound assets into. */
	static const TCHAR* SoundPackageDir();

	/** The per-sound asset name for an event: "S_" + the event name. */
	static FString SoundAssetNameFor(FName Event);

	/** The full convention path for an event's sound, used when the bank has no row for it. */
	static FString ConventionPathFor(FName Event);
};

/**
 * Project Settings > Game > Trace Audio.
 *
 * Deliberately its OWN settings object rather than nine more knobs on UTraceSettings: this is a new
 * system landing beside eight other agents' edits, and a separate UDeveloperSettings is a new file
 * and a new ini section instead of a merge conflict in the two most-edited files in the project.
 *
 * Nothing here is REQUIRED to be in Config/DefaultGame.ini — the header defaults are the shipped
 * tuning. Editing any of these in Project Settings writes the section for you.
 */
UCLASS(config = Game, defaultconfig, meta = (DisplayName = "Trace Audio"))
class TRACE_API UTraceAudioSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	UTraceAudioSettings();

	virtual FName GetCategoryName() const override;

	static const UTraceAudioSettings& Get();

	/** Master switch. False silences the whole bank without unwiring a single call site. */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Sound Effects Enabled"))
	bool bSoundEffectsEnabled = true;

	/** The bank asset. Point this at a different bank to swap the whole set at once. */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Sound Bank Asset", AllowedClasses = "/Script/Trace.TraceSoundBank"))
	FSoftObjectPath SoundBankPath;

	/** THE BASE VOLUME every play is scaled from. Per-event trims in the bank multiply this. */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Master Volume", ClampMin = "0.0", ClampMax = "4.0", UIMin = "0.0", UIMax = "2.0"))
	float MasterVolume = 1.f;

	/**
	 * THE BASE RADIUS of a game-side sound: everyone inside this hears it at full volume.
	 *
	 * 1200 uu is roughly a fifth of the arena's short axis, so a dash next to you is loud and a dash
	 * across the field is not.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Game-Side Inner Radius (uu)", ClampMin = "50.0", ClampMax = "20000.0", UIMin = "200.0", UIMax = "5000.0"))
	float WorldInnerRadiusUU = 1200.f;

	/**
	 * How far the falloff runs PAST the inner radius, AS A MULTIPLE OF IT — not as an absolute
	 * distance.
	 *
	 * THIS PROJECT'S STANDING RULE, applied: the falloff MODIFIES the inner radius, so it is stored
	 * relative to it and moves when it moves. Widening the inner radius to 2400 keeps the same shape
	 * (audible out to 2400 + 2400x5) instead of collapsing the falloff to a hard edge, which is what
	 * an absolute "FalloffDistance = 6000" would have done silently.
	 */
	UPROPERTY(config, EditAnywhere, Category = "Trace|Audio", meta = (DisplayName = "Game-Side Falloff (x inner radius)", ClampMin = "0.1", ClampMax = "50.0", UIMin = "1.0", UIMax = "12.0"))
	float WorldFalloffScale = 5.f;

	/** The audible edge of a game-side sound. Derived, never stored. */
	float GetWorldFalloffDistanceUU() const;
};
