# =============================================================================
# Trace — retarget_rocco.py
#
# Runs INSIDE the editor (UnrealEditor-Cmd -run=pythonscript). Makes Rocco MOVE.
#
# Driven by Scripts/retarget-rocco.sh — do not invoke this by hand.
#
#   /Game/Characters/Mannequins/Anims/Unarmed/ABP_Unarmed   (Epic's, untouched)
#        |
#        |   IK_Manny  ->  RTG_Manny_To_Rocco  ->  IK_Rocco
#        v
#   /Game/Trace/Characters/Rocco/Anims/ABP_Unarmed_Rocco    AnimBlueprint on
#                                                           SK_Rocco_Skeleton
#   ...plus every sequence and blend space it refers to, duplicated and
#      retargeted beside it.
#
# WHY A RETARGET AND NOT A RENAME
#
#   SK_Rocco is skinned to SK_Rocco_Skeleton, whose bones are Hips1 / Spine021 /
#   LeftHand1 / RightHand1 — a generic Mixamo-shaped rig with a trailing "1" on
#   every name (Scripts/import_rocco.py's header explains where the "1" comes
#   from and why a commandlet cannot remove it). ABP_Unarmed is bound to the
#   MANNEQUIN's skeleton: root / pelvis / spine_01 / hand_r. Zero names in
#   common, so the engine has nothing to drive and SK_Rocco is drawn in its bind
#   pose, sliding around the arena.
#
#   Renaming the bones would not have been enough even if it were possible.
#   An AnimSequence stores LOCAL bone rotations that REPLACE the target's
#   reference pose, so playing Manny's walk on a rig whose bind pose and bone
#   axes differ produces a correctly-named, badly-broken pose. What makes the
#   two rigs comparable is the RETARGET POSE, and that is what an IK Retargeter
#   is for. Hence: two IK Rigs, one Retargeter, and an OFFLINE batch retarget
#   that bakes the answer into ordinary AnimSequences.
#
# OFFLINE, NOT AT RUNTIME, AND THAT IS THE WHOLE POINT
#
#   The other way to do this is a "Retarget Pose From Mesh" node, which needs a
#   SECOND hidden skeletal mesh component per pawn running ABP_Unarmed, plus a
#   runtime dependency on the IKRig module, and pays for the retarget every
#   frame on every Rocco in the match. Baking instead means the shipped game
#   plays a plain AnimBlueprint over plain AnimSequences and never loads an IK
#   Rig at all: the three assets this script writes under Retarget/ are editor
#   inputs, referenced by nothing the game packages.
#
# THE THREE ASSETS, AND WHY EACH KNOB IS WHERE IT IS
#
#   IK_Manny   built by ApplyAutoGeneratedRetargetDefinition(), which recognises
#              SKM_Manny_Simple as the engine's own "UE5 Mannequin" template and
#              writes the chains for it. The result is CHECKED against the chain
#              names this script needs rather than trusted — if a future engine
#              renames a chain, the run fails here instead of producing a
#              retargeter that maps nothing.
#
#   IK_Rocco   built BY HAND from the table below. Auto-characterisation cannot
#              work on this rig and it is worth knowing why: the matcher strips
#              the largest COMMON PREFIX from the bone names and then compares
#              them to its templates. Rocco's suffix is not a prefix, so "Hips1"
#              never becomes "Hips", nothing matches Mixamo, and the auto
#              definition comes back empty. The script asks anyway and REPORTS
#              the answer, because "it did not match" is worth printing once.
#
#   RTG        source IK_Manny, target IK_Rocco, chains mapped by EXACT name —
#              which is why Rocco's chains are named for Epic's own
#              FCharacterizationStandard constants (Spine, LeftArm, RightLeg...)
#              rather than for his bones.
#
#   Two ops, not the engine's default five. PelvisMotion carries the hips
#   (height, bob, translation); FKChains rotates everything else. The default
#   stack also adds RunIKRig, RootMotion and CurveRemap:
#     - RunIKRig needs IK goals and a solver, and IK_Rocco has neither. It would
#       initialise to nothing and warn once per run.
#     - RootMotion would write keys onto Rocco's root ("target_character"). Every
#       sequence ABP_Unarmed plays is IN PLACE — the game moves the capsule — so
#       the right answer for the root bone is "no keys at all".
#     - CurveRemap has no curves to remap between these two rigs.
#
#   AutoAlignAllBones(TARGET, ChainToChain) is what makes the retarget POSE, and
#   it is the step that decides whether the result looks like a person walking or
#   like a person walking with their arms on backwards. It rotates each of
#   Rocco's bones so his chains point the way Manny's do, which is how an A-pose
#   rig and a T-pose rig are made comparable without anybody opening an editor.
#
# WHAT IS CHECKED RATHER THAN ASSUMED
#
#   Every step that can silently do nothing is read back: the chains land on the
#   rig, the op stack is the one asked for, every target chain resolves to a
#   source chain, the batch produces files, the duplicated AnimBlueprint really
#   is bound to SK_Rocco_Skeleton, and — the one that actually matters — the
#   retargeted sequences MOVE. The last check samples a thigh bone at three
#   frames and fails if the pose is constant, because a retarget that quietly
#   produced a bind pose on every frame would otherwise pass every other test in
#   this file.
# =============================================================================
import os
import unreal


ROCCO_MESH_PATH = "/Game/Trace/Characters/Rocco/SK_Rocco"
ROCCO_SKELETON_PATH = "/Game/Trace/Characters/Rocco/SK_Rocco_Skeleton"
MANNY_MESH_PATH = "/Game/Characters/Mannequins/Meshes/SKM_Manny_Simple"
SOURCE_ABP_PATH = "/Game/Characters/Mannequins/Anims/Unarmed/ABP_Unarmed"

RIG_DIR = "/Game/Trace/Characters/Rocco/Retarget"
ANIM_DIR = "/Game/Trace/Characters/Rocco/Anims"

IK_MANNY_NAME = "IK_Manny"
IK_ROCCO_NAME = "IK_Rocco"
RTG_NAME = "RTG_Manny_To_Rocco"

IK_MANNY_PATH = "{0}/{1}".format(RIG_DIR, IK_MANNY_NAME)
IK_ROCCO_PATH = "{0}/{1}".format(RIG_DIR, IK_ROCCO_NAME)
RTG_PATH = "{0}/{1}".format(RIG_DIR, RTG_NAME)

# The suffix every duplicated animation asset gets. It is also what the C++ side
# spells out in TraceCharacterRoster's Rocco row, so changing it here is a
# two-file change.
NAME_SUFFIX = "_Rocco"
RESULT_ABP_PATH = "{0}/ABP_Unarmed{1}".format(ANIM_DIR, NAME_SUFFIX)

# Rocco's retarget chains, named for Epic's FCharacterizationStandard constants
# (IKRigAutoCharacterizer.cpp) because the retargeter maps source to target BY
# CHAIN NAME and IK_Manny's chains come from that same table. The bone names are
# this rig's real ones, trailing "1" and all — see the header.
#
# Rocco has 24 bones and no fingers, so the eleven chains below are all of him
# that can be retargeted. Manny's finger chains simply find no counterpart and
# are left alone, which is correct: the hands stay in their bind pose, and this
# character's hands are mittens.
#
#   chain name        start bone       end bone
ROCCO_CHAINS = (
    ("Spine",         "Spine021",      "Spine1"),
    ("Neck",          "neck1",         "neck1"),
    ("Head",          "Head1",         "Head1"),
    ("LeftClavicle",  "LeftShoulder1", "LeftShoulder1"),
    ("RightClavicle", "RightShoulder1", "RightShoulder1"),
    ("LeftArm",       "LeftArm1",      "LeftHand1"),
    ("RightArm",      "RightArm1",     "RightHand1"),
    ("LeftLeg",       "LeftUpLeg1",    "LeftFoot1"),
    ("RightLeg",      "RightUpLeg1",   "RightFoot1"),
    ("LeftFoot",      "LeftToeBase1",  "LeftToeBase1"),
    ("RightFoot",     "RightToeBase1", "RightToeBase1"),
)
ROCCO_PELVIS = "Hips1"

# The chains IK_Manny MUST end up with for the mapping above to find anything.
# Checked, not assumed: ApplyAutoGeneratedRetargetDefinition is engine code and
# a renamed constant would otherwise leave a retargeter that maps nothing.
REQUIRED_MANNY_CHAINS = tuple(name for name, _s, _e in ROCCO_CHAINS)

# Full UStruct paths — AddRetargetOp resolves them with FindObject<UScriptStruct>.
OP_PELVIS = "/Script/IKRig.IKRetargetPelvisMotionOp"
OP_FK_CHAINS = "/Script/IKRig.IKRetargetFKChainsOp"

FORCE = os.environ.get("TRACE_FORCE_ROCCO_RETARGET", "0") == "1"

EAL = unreal.EditorAssetLibrary

_failures = []


def log(msg):
    unreal.log("[Trace] {0}".format(msg))


def fail(msg):
    _failures.append(msg)
    unreal.log_error("[Trace] {0}".format(msg))


def load(path, what):
    asset = EAL.load_asset(path)
    if asset is None:
        fail("{0} is missing: {1}".format(what, path))
    return asset


def create_asset(name, folder, cls, factory):
    """Create, replacing whatever is there. The package files are deleted by the
    shell BEFORE the editor starts (see retarget-rocco.sh) for the reason
    Scripts/import-rocco.sh spells out: delete_asset frees the file but leaves
    the Asset Registry entry behind for the rest of the session, so a same-run
    create-over-delete silently hands back the OLD object."""
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    asset = tools.create_asset(name, folder, cls, factory)
    if asset is None:
        fail("could not create {0}/{1}".format(folder, name))
    return asset


# -----------------------------------------------------------------------------
# IK_Manny — the source rig.
# -----------------------------------------------------------------------------
def build_manny_rig(manny_mesh):
    rig = create_asset(IK_MANNY_NAME, RIG_DIR, unreal.IKRigDefinition,
                       unreal.IKRigDefinitionFactory())
    if rig is None:
        return None

    controller = unreal.IKRigController.get_controller(rig)
    if not controller.set_skeletal_mesh(manny_mesh):
        fail("IK_Manny rejected SKM_Manny_Simple")
        return None

    # Engine code, and it knows this skeleton by name: SKM_Manny_Simple matches
    # the "UE5 Mannequin" template exactly, so the chains, the pelvis and the
    # root bone all come from Epic's own characterisation rather than from a
    # table in this file that could drift from it.
    matched = controller.apply_auto_generated_retarget_definition()
    log("  IK_Manny       auto-characterise -> {0}".format("MATCHED" if matched else "no template matched"))
    if not matched:
        fail("the auto-characteriser did not recognise SKM_Manny_Simple; IK_Manny has no chains")
        return None

    got = set(str(chain.get_editor_property("chain_name")) for chain in controller.get_retarget_chains())
    missing = [c for c in REQUIRED_MANNY_CHAINS if c not in got]
    if missing:
        fail("IK_Manny is missing chain(s) this retarget maps: {0}".format(", ".join(missing)))
    log("  IK_Manny       {0} chain(s), pelvis {1!r}, root-motion bone {2!r}"
        .format(len(got), str(controller.get_retarget_root()), str(controller.get_root_motion_bone())))
    return rig


# -----------------------------------------------------------------------------
# IK_Rocco — the target rig, built by hand from ROCCO_CHAINS.
# -----------------------------------------------------------------------------
def build_rocco_rig(rocco_mesh):
    rig = create_asset(IK_ROCCO_NAME, RIG_DIR, unreal.IKRigDefinition,
                       unreal.IKRigDefinitionFactory())
    if rig is None:
        return None

    controller = unreal.IKRigController.get_controller(rig)
    if not controller.set_skeletal_mesh(rocco_mesh):
        fail("IK_Rocco rejected SK_Rocco")
        return None

    # Asked, and reported, and then overwritten. See the header: the matcher
    # cannot strip a trailing "1", so this is expected to come back False. It is
    # here so that the day the art is re-exported with clean bone names, the
    # report says so out loud instead of this file silently going on doing it the
    # hard way.
    matched = controller.apply_auto_generated_retarget_definition()
    log("  IK_Rocco       auto-characterise -> {0}"
        .format("MATCHED (the rig's bone names are now clean enough for the engine's "
                "own templates; the hand-written chains below are no longer the only option)"
                if matched else "no template matched, as expected for this rig's bone names"))

    for name, start, end in ROCCO_CHAINS:
        given = str(controller.add_retarget_chain(name, start, end, ""))
        if given != name:
            # A uniquified name (Spine_0) means the auto pass above left a chain
            # of the same name behind, and the mapping by exact name would then
            # find the WRONG one.
            fail("IK_Rocco chain {0!r} came back named {1!r}".format(name, given))

    if not controller.set_retarget_root(ROCCO_PELVIS):
        fail("IK_Rocco rejected pelvis bone {0!r}".format(ROCCO_PELVIS))

    # Read back off the asset rather than trusting the setters.
    by_name = {}
    for chain in controller.get_retarget_chains():
        by_name[str(chain.get_editor_property("chain_name"))] = (
            str(chain.get_editor_property("start_bone").get_editor_property("bone_name")),
            str(chain.get_editor_property("end_bone").get_editor_property("bone_name")))
    for name, start, end in ROCCO_CHAINS:
        landed = by_name.get(name)
        if landed is None:
            fail("IK_Rocco chain {0!r} did not land".format(name))
        elif landed != (start, end):
            fail("IK_Rocco chain {0!r} landed as {1} -> {2}, expected {3} -> {4}"
                 .format(name, landed[0], landed[1], start, end))
    log("  IK_Rocco       {0} chain(s), pelvis {1!r}"
        .format(len(by_name), str(controller.get_retarget_root())))
    return rig


# -----------------------------------------------------------------------------
# The retargeter.
# -----------------------------------------------------------------------------
def build_retargeter(manny_rig, rocco_rig, manny_mesh, rocco_mesh):
    rtg = create_asset(RTG_NAME, RIG_DIR, unreal.IKRetargeter, unreal.IKRetargetFactory())
    if rtg is None:
        return None

    controller = unreal.IKRetargeterController.get_controller(rtg)
    controller.set_ik_rig(unreal.RetargetSourceOrTarget.SOURCE, manny_rig)
    controller.set_ik_rig(unreal.RetargetSourceOrTarget.TARGET, rocco_rig)
    controller.set_preview_mesh(unreal.RetargetSourceOrTarget.SOURCE, manny_mesh)
    controller.set_preview_mesh(unreal.RetargetSourceOrTarget.TARGET, rocco_mesh)

    # Two ops, added AFTER the rigs so each one's OnAddedToStack sees them. The
    # header says why these two and not the engine's default five.
    for op_type in (OP_PELVIS, OP_FK_CHAINS):
        if controller.add_retarget_op(op_type) < 0:
            fail("retargeter rejected op type {0}".format(op_type))
    controller.assign_ik_rig_to_all_ops(unreal.RetargetSourceOrTarget.SOURCE, manny_rig)
    controller.assign_ik_rig_to_all_ops(unreal.RetargetSourceOrTarget.TARGET, rocco_rig)

    # EXACT, not FUZZY. Rocco's chains are deliberately named for Epic's own
    # constants precisely so that an exact match is possible; a fuzzy match here
    # would paper over a typo in ROCCO_CHAINS instead of failing on it.
    controller.auto_map_chains(unreal.AutoMapChainType.EXACT, True)

    unmapped = []
    for name, _s, _e in ROCCO_CHAINS:
        source = str(controller.get_source_chain(name))
        if source != name:
            unmapped.append("{0} -> {1!r}".format(name, source))
    if unmapped:
        fail("chain(s) did not map onto IK_Manny: {0}".format(", ".join(unmapped)))

    ops = [str(controller.get_op_name(i)) for i in range(controller.get_num_retarget_ops())]
    log("  RTG            op stack: {0}".format(", ".join(ops) if ops else "EMPTY"))
    if len(ops) != 2:
        fail("expected exactly 2 retarget ops, got {0}".format(len(ops)))

    # THE STEP THAT DECIDES WHETHER IT LOOKS RIGHT. Rotates each of Rocco's bones
    # until his chains point the way Manny's do, so the two bind poses become
    # comparable. Without it an A-pose rig driven by a T-pose rig's animation
    # wears the difference for the whole match.
    controller.auto_align_all_bones(unreal.RetargetSourceOrTarget.TARGET,
                                    unreal.RetargetAutoAlignMethod.CHAIN_TO_CHAIN)

    # Printed per chain rather than counted, because "5 of 11" is not a fact
    # anyone can act on. A chain with NO offset is not a failure — it means Rocco
    # already points the way Manny does there — but a run where the ARMS came back
    # identity would mean the align silently did nothing, and that is worth being
    # able to see at a glance.
    offsets = []
    for name, start, _end in ROCCO_CHAINS:
        offset = controller.get_rotation_offset_for_retarget_pose_bone(
            start, unreal.RetargetSourceOrTarget.TARGET)
        # As a rotator, not as an angle against a default-constructed FQuat:
        # unreal.Quat() comes back ZEROED rather than identity, and comparing
        # against it reports a flat 180 degrees for every bone that moved at all.
        # That reads exactly like "the align turned everything around" and sent
        # this script's author looking for a bug that was in the yardstick.
        rot = offset.rotator()
        offsets.append("{0} ({1:.0f},{2:.0f},{3:.0f})".format(
            name, rot.pitch, rot.yaw, rot.roll))
    log("  RTG            retarget pose {0!r}, per-chain align offset as (pitch,yaw,roll): {1}"
        .format(str(controller.get_current_retarget_pose_name(unreal.RetargetSourceOrTarget.TARGET)),
                ", ".join(offsets)))
    return rtg


# -----------------------------------------------------------------------------
# The batch.
# -----------------------------------------------------------------------------
def run_batch(rtg, manny_mesh, rocco_mesh, source_abp):
    inputs = unreal.IKRetargetBatchOperationInputs()
    inputs.set_editor_property("assets_to_retarget",
                               [unreal.AssetRegistryHelpers.get_asset_registry()
                                .get_asset_by_object_path(SOURCE_ABP_PATH + ".ABP_Unarmed")])
    inputs.set_editor_property("source_mesh", manny_mesh)
    inputs.set_editor_property("target_mesh", rocco_mesh)
    inputs.set_editor_property("ik_retarget_asset", rtg)
    inputs.set_editor_property("suffix", NAME_SUFFIX)
    inputs.set_editor_property("target_path", ANIM_DIR)
    inputs.set_editor_property("use_source_path", False)
    # The blueprint is only the entry point: what has to be retargeted is every
    # sequence and blend space it plays.
    inputs.set_editor_property("include_referenced_assets", True)
    inputs.set_editor_property("overwrite_existing_files", True)

    created = unreal.IKRetargetBatchOperation.run_batch_retarget(inputs)
    names = sorted(str(a.get_editor_property("package_name")) for a in created)
    log("  batch          {0} asset(s) written".format(len(names)))
    for n in names:
        log("                   {0}".format(n))
    if not names:
        fail("the batch retarget produced nothing at all")
    return names


# -----------------------------------------------------------------------------
# The checks that matter.
# -----------------------------------------------------------------------------
def bone_names(mesh):
    subsystem = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    actor = subsystem.spawn_actor_from_class(
        unreal.SkeletalMeshActor, unreal.Vector(0, 0, 0), unreal.Rotator(0, 0, 0))
    if actor is None:
        return []
    try:
        comp = actor.skeletal_mesh_component
        comp.set_skeletal_mesh_asset(mesh)
        return [str(comp.get_bone_name(i)) for i in range(comp.get_num_bones())]
    finally:
        subsystem.destroy_actor(actor)


def check_result(rocco_skeleton):
    """The blueprint is on the right skeleton, and the animation actually moves."""
    abp = EAL.load_asset(RESULT_ABP_PATH)
    if abp is None:
        fail("the retargeted anim blueprint is not at {0}".format(RESULT_ABP_PATH))
        return

    target = abp.get_editor_property("target_skeleton")
    if target != rocco_skeleton:
        fail("{0} targets skeleton {1}, not {2}"
             .format(RESULT_ABP_PATH, target.get_path_name() if target else "None",
                     rocco_skeleton.get_path_name()))
    else:
        log("  ABP            ABP_Unarmed{0} targets {1}".format(NAME_SUFFIX, target.get_name()))

    # The class, not the blueprint, is what ATraceCharacter::CharacterAnimClass
    # points at, and a blueprint that failed to compile still loads perfectly
    # well as an asset. Ask for the generated class by the name the game will
    # use.
    generated = EAL.load_blueprint_class(RESULT_ABP_PATH)
    if generated is None:
        fail("{0} has no generated class — it did not compile, so nothing can run it"
             .format(RESULT_ABP_PATH))
    else:
        log("  ABP            generated class {0}".format(generated.get_name()))

    # *** THE CHECK THIS WHOLE SCRIPT EXISTS FOR. *** Every step above can succeed
    # and still leave sequences that are the bind pose on every frame — which is
    # exactly the state this task was handed, and it is invisible to every other
    # test in this file. So the pose is SAMPLED, and two different things are
    # asked of it:
    #
    #   1. NOTHING IS FROZEN. A sequence whose sampled pose never changes at all
    #      is a bind pose wearing a duration. The threshold is deliberately near
    #      zero, because MM_Idle legitimately barely moves — an idle that breathes
    #      is 1 degree of spine, and demanding more of it would be a harness
    #      measuring the wrong thing.
    #   2. SOMETHING REALLY WALKS. Across the whole set, at least one sequence has
    #      to swing a leg like a locomotion cycle does. This is the arm that would
    #      catch a retarget that produced correct-but-tiny noise everywhere.
    FROZEN_DEGREES = 0.05
    WALK_DEGREES = 20.0
    SAMPLED_BONES = ("LeftUpLeg1", "RightUpLeg1", "LeftArm1", "Spine021")
    checked = 0
    loudest = 0.0
    loudest_name = ""
    for path in sorted(EAL.list_assets(ANIM_DIR, recursive=True, include_folder=False)):
        anim = EAL.load_asset(path)
        if not isinstance(anim, unreal.AnimSequence):
            continue
        frames = unreal.AnimationLibrary.get_num_frames(anim)
        if frames < 2:
            continue
        moved = 0.0
        for bone in SAMPLED_BONES:
            samples = [unreal.AnimationLibrary.get_bone_pose_for_frame(anim, bone, f, False).rotation
                       for f in sorted(set((frames - 1) * i // 8 for i in range(9)))]
            for a in range(len(samples)):
                for b in range(a + 1, len(samples)):
                    moved = max(moved, abs(samples[a].angular_distance(samples[b])))
        checked += 1
        degrees = moved * 180.0 / 3.14159265358979
        if degrees > loudest:
            loudest, loudest_name = degrees, anim.get_name()
        log("  motion         {0:<44} {1:>3} frames, {2:6.2f} deg  {3}"
            .format(anim.get_name(), frames, degrees,
                    "moves" if degrees > FROZEN_DEGREES else "*** FROZEN ***"))
        if degrees <= FROZEN_DEGREES:
            fail("{0} is frozen: across 9 samples of 4 bones the pose never changes by more "
                 "than {1:.3f} degrees. That is a bind pose with a duration, which is exactly "
                 "what this retarget exists to replace.".format(anim.get_name(), degrees))
    if loudest < WALK_DEGREES:
        fail("nothing in {0} swings a limb: the widest rotation anywhere in {1} sequence(s) is "
             "{2:.2f} degrees ({3}), and a walk cycle is tens of degrees. The retarget ran but "
             "carried almost no animation.".format(ANIM_DIR, checked, loudest, loudest_name))
    else:
        log("  motion         widest swing {0:.1f} deg in {1}".format(loudest, loudest_name))
    if checked == 0:
        fail("no retargeted AnimSequence was found under {0} to check for motion".format(ANIM_DIR))


# -----------------------------------------------------------------------------
def main():
    log("=" * 78)
    log("ROCCO RETARGET")
    log("=" * 78)

    rocco_mesh = load(ROCCO_MESH_PATH, "SK_Rocco")
    rocco_skeleton = load(ROCCO_SKELETON_PATH, "SK_Rocco_Skeleton")
    manny_mesh = load(MANNY_MESH_PATH, "SKM_Manny_Simple")
    source_abp = load(SOURCE_ABP_PATH, "ABP_Unarmed")
    if _failures:
        report()
        return

    # The chain table names bones. If the art is re-imported and a bone name
    # moves, every setter below quietly does nothing and the retarget comes out
    # as a bind pose — so the names are checked against the mesh FIRST.
    present = set(bone_names(rocco_mesh))
    wanted = set([ROCCO_PELVIS])
    for _n, s, e in ROCCO_CHAINS:
        wanted.add(s)
        wanted.add(e)
    absent = sorted(b for b in wanted if b not in present)
    if absent:
        fail("SK_Rocco has no bone(s) named: {0}. ROCCO_CHAINS in this script is out of "
             "date with the import.".format(", ".join(absent)))
        report()
        return
    log("  bones          all {0} bone(s) ROCCO_CHAINS names are present on SK_Rocco".format(len(wanted)))

    manny_rig = build_manny_rig(manny_mesh)
    rocco_rig = build_rocco_rig(rocco_mesh)
    if _failures:
        report()
        return

    rtg = build_retargeter(manny_rig, rocco_rig, manny_mesh, rocco_mesh)
    if _failures:
        report()
        return

    EAL.save_loaded_asset(manny_rig, False)
    EAL.save_loaded_asset(rocco_rig, False)
    EAL.save_loaded_asset(rtg, False)

    run_batch(rtg, manny_mesh, rocco_mesh, source_abp)
    unreal.EditorLoadingAndSavingUtils.save_dirty_packages(False, True)
    check_result(rocco_skeleton)
    report()


def report():
    log("-" * 78)
    if _failures:
        log("{0} PROBLEM(S)".format(len(_failures)))
        for f in _failures:
            log("  - {0}".format(f))
    else:
        log("no problems reported")
    log("=" * 78)


main()
