// Trace — the title screen as a UMG widget (spec v17 §4).
//
// ---------------------------------------------------------------------------------------------
// WHAT MOVED AND WHAT DID NOT
// ---------------------------------------------------------------------------------------------
// NOTHING about how the title screen BEHAVES moved. ATraceMenuHUD still owns every piece of state
// it owned before — which row is selected, which difficulty, which scoring mode, the press/release
// arming, the cursor-has-moved discriminator, the activation grace period — and still runs every
// one of its harnesses (-TraceAutoPlay, -TraceAutoJoin, -TraceAutoSettings, -TraceMenuClickTest).
// Spec v17 §0: this is a reorganisation, and a behaviour change would be a bug.
//
// What moved is the PIXELS. This widget is a view: once per frame the HUD hands it an
// FTraceTitleMenuView and it puts that on screen. It reads no game state, calls no gameplay code
// and makes no decision. That is what keeps the two renderers honest — they are driven from the
// same state by the same file, so `Trace.UI.VerifyMenu` can compare them.
//
// ---------------------------------------------------------------------------------------------
// HIT TESTING STAYS IN THE HUD, AND THAT IS THE WHOLE TRICK
// ---------------------------------------------------------------------------------------------
// The obvious UMG port makes every row a UButton and lets Slate route the clicks. That would have
// thrown away spec v15 §4's single-press work and the cursor-movement defence in one move, because
// Slate's button semantics are not this menu's semantics.
//
// So this widget is entirely HitTestInvisible and takes no input at all. Instead it reports where
// its rows LANDED — GetRowViewportRect() converts each row's Slate geometry into the same viewport
// pixel space APlayerController::GetMousePosition works in — and ATraceMenuHUD keeps using its own
// RowAtPoint / MousePressed / MouseReleased exactly as written. The click path is the same code on
// both renderers; only the source of the rectangles changes.
//
// ---------------------------------------------------------------------------------------------
// EVERY BindWidget NAME BELOW MUST EXIST IN Content/Trace/UI/Menu/WBP_TitleMenu
// ---------------------------------------------------------------------------------------------
// Rename or delete one in the editor and the Blueprint fails to compile with the missing name in
// the message. That loud failure is the safety net spec v17 §4 asks for, and it is why the asset is
// generated by Scripts/generate-menu-widgets.py from this header's names rather than drawn by hand.

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "Math/Box2D.h"

#include "UI/Widgets/Menu/TraceMenuRowWidget.h"

#include "TraceTitleMenuWidget.generated.h"

class UBorder;
class UImage;
class UTextBlock;

/** One frame of the title screen, as ATraceMenuHUD sees it. */
struct FTraceTitleMenuView
{
	static constexpr int32 MaxRows = 8;

	int32 RowCount = 0;
	FTraceMenuRowView Rows[MaxRows];

	/** One line of plain English under the rows, describing the SELECTED row. */
	FString Blurb;

	FString Tagline;
	FString AddressCaption;
	FString AddressValue;

	/** Empty unless UDP 7777 is already taken on this machine, in which case the chip is a lie. */
	FString PortWarning;

	FString FooterKeys;
	FString FooterHint;

	bool bFailureVisible = false;
	FString FailureHeadline;
	FString FailureDetail;
	float FailureFade = 1.f;

	bool bTravelVisible = false;
	FString TravelCaption;
	/** Only a join can sit here for a noticeable time; a local map load is instant. */
	FString TravelHint;

	bool bCursorVisible = false;
	/** 0..1 across the viewport. Fractions, so nothing here depends on the DPI scale. */
	FVector2D CursorFraction = FVector2D(0.5, 0.5);

	float Now = 0.f;
};

/**
 * The title screen. Created by ATraceMenuHUD when `Trace.UI.UseUMG` is on and
 * /Game/Trace/UI/Menu/WBP_TitleMenu loads; absent either, the HUD draws its Canvas path instead and
 * says so in the log.
 */
UCLASS()
class TRACE_API UTraceTitleMenuWidget : public UUserWidget
{
	GENERATED_BODY()

public:
	/** Pushes one frame of state onto the tree. Called once per DrawHUD; makes no decisions. */
	void ApplyView(const FTraceTitleMenuView& InView);

	/**
	 * The row's rectangle in VIEWPORT PIXELS — the space APlayerController::GetMousePosition and
	 * ATraceMenuHUD::RowRects both work in.
	 *
	 * @return false before the row has ever been laid out, which is the first frame and only the
	 *         first frame. The HUD leaves bRowRectsValid false until every row answers, exactly as
	 *         the Canvas path leaves it false until the first DrawMenuRows.
	 */
	bool GetRowViewportRect(int32 InRowIndex, FBox2D& OutRect) const;

	/** How many rows the asset actually provides. Six today; the HUD asserts it matches its enum. */
	int32 GetRowCount() const { return OrderedRows.Num(); }

	/**
	 * Every sprite this screen is supposed to be made of, and whether it actually arrived.
	 *
	 * `Trace.UI.VerifyMenuArt` prints it. It exists because a UImage with no texture in its brush is
	 * drawn by Slate as a plain WHITE RECTANGLE, not as nothing — so a menu missing half the artist's
	 * art does not look broken, it looks like a different design, and nobody investigates.
	 *
	 * @param bIncludeBackdrop  THE RED ARM. Backdrop is the one image on this screen that is SUPPOSED
	 *                          to have no texture — it is a flat black fill — so including it must
	 *                          make this report a missing sprite. If it does not, the "has a texture"
	 *                          test cannot return false and none of its passes mean anything.
	 * @return the number of sprite slots that resolved; @p OutTotal is how many there are.
	 */
	int32 CountResolvedArt(int32& OutTotal, TArray<FString>& OutMissing, bool bIncludeBackdrop = false) const;

	//~ Begin UUserWidget interface
	virtual void NativeOnInitialized() override;
	//~ End UUserWidget interface

protected:
	// ---- The art layers, bottom to top (spec v19 §5) -----------------------------------------------
	//
	// The stroke-drawn backdrop is gone. The brief was explicit — "Keep the background black" — so
	// Backdrop is now a plain black fill and the grid floor, the horizon glow and the bezel that used
	// to sit on it are not drawn at all. What is on the black is the artist's: their swoosh, their
	// wordmark, their buttons, their cursor.

	/** Black. Opaque, and first, so the empty menu map behind it can never show through. */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> Backdrop;

	/** The white sweep from the sheet, behind the title. Decorative; never hit-tested. */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> SwooshImage;

	/**
	 * The TRACE mark, as the artist drew it.
	 *
	 * This replaces UTraceStrokeText, whose five hand-built glyphs were the second of the two reasons
	 * `Trace.UI.UseUMG` was turned off in v17: at the widget path's stroke thickness the R came apart
	 * and the A's point was chopped. A sprite has no thickness to get wrong.
	 */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> Wordmark;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TaglineText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> AddressChip;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> AddressCaptionText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> AddressValueText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> PortWarningText;

	// ---- The console -----------------------------------------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> ConsolePanel;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowPlay;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowJoin;

	/** Spec v19 §2, the practice range. Third, with PLAY and JOIN — see ETraceMenuRow::Practice. */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowPractice;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowDifficulty;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowMode;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowSettings;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowQuit;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> BlurbText;

	// ---- Footer, frame, cursor -------------------------------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FooterKeysText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FooterHintText;

	/**
	 * The artist's pointer, and the reason the OS cursor is not it.
	 *
	 * Moved by re-anchoring rather than by an offset, so it lands in the same place whatever the DPI
	 * scale is: ATraceMenuHUD hands over a 0..1 fraction of the viewport and this sets the anchor to
	 * it. The sprite's tip is its top-left corner, which is why the alignment is (0,0).
	 */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> MenuCursor;

	// ---- The two things that outrank everything else ---------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> TravelOverlay;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> TravelWordmark;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TravelCaptionText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TravelHintText;

	/**
	 * Over the travel overlay, and over the join prompt on the Canvas path. Measured from a
	 * screenshot: drawn earlier, a modal's 78%-black scrim turned the one message the player most
	 * needs to read into a dim brown smudge.
	 */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> FailureBanner;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FailureHeadlineText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FailureDetailText;

private:
	/**
	 * Reproduces the Canvas path's min(width * 0.52, 720) console clamp, which no canvas-panel
	 * anchor can express. See the comment at the call site in ApplyView.
	 */
	void SyncConsoleWidth();

	/** The six rows in ETraceMenuRow order, resolved once. Empty before NativeOnInitialized. */
	UPROPERTY(Transient)
	TArray<TObjectPtr<UTraceMenuRow>> OrderedRows;
};
