// Trace — the title screen as a UMG widget (spec v17 §4).
//
// ---------------------------------------------------------------------------------------------
// WHAT MOVED AND WHAT DID NOT
// ---------------------------------------------------------------------------------------------
// NOTHING about how the title screen BEHAVES moved. ATraceMenuHUD still owns every piece of state
// it owned before — which row is selected, which difficulty, which scoring mode, the press/release
// arming, the cursor-has-moved discriminator, the activation grace period — and still runs every
// one of its harnesses (-TraceAutoPlay, -TraceAutoJoin, -TraceAutoSettings, -TraceMenuClickTest).
// Spec v17 §0: this is a reorganisation, and a behaviour change would be a bug.
//
// What moved is the PIXELS. This widget is a view: once per frame the HUD hands it an
// FTraceTitleMenuView and it puts that on screen. It reads no game state, calls no gameplay code
// and makes no decision. That is what keeps the two renderers honest — they are driven from the
// same state by the same file, so `Trace.UI.VerifyMenu` can compare them.
//
// ---------------------------------------------------------------------------------------------
// HIT TESTING STAYS IN THE HUD, AND THAT IS THE WHOLE TRICK
// ---------------------------------------------------------------------------------------------
// The obvious UMG port makes every row a UButton and lets Slate route the clicks. That would have
// thrown away spec v15 §4's single-press work and the cursor-movement defence in one move, because
// Slate's button semantics are not this menu's semantics.
//
// So this widget is entirely HitTestInvisible and takes no input at all. Instead it reports where
// its rows LANDED — GetRowViewportRect() converts each row's Slate geometry into the same viewport
// pixel space APlayerController::GetMousePosition works in — and ATraceMenuHUD keeps using its own
// RowAtPoint / MousePressed / MouseReleased exactly as written. The click path is the same code on
// both renderers; only the source of the rectangles changes.
//
// ---------------------------------------------------------------------------------------------
// EVERY BindWidget NAME BELOW MUST EXIST IN Content/Trace/UI/Menu/WBP_TitleMenu
// ---------------------------------------------------------------------------------------------
// Rename or delete one in the editor and the Blueprint fails to compile with the missing name in
// the message. That loud failure is the safety net spec v17 §4 asks for, and it is why the asset is
// generated by Scripts/generate-menu-widgets.py from this header's names rather than drawn by hand.

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "Math/Box2D.h"

#include "UI/Widgets/Menu/TraceMenuRowWidget.h"

#include "TraceTitleMenuWidget.generated.h"

class UBorder;
class UTextBlock;
class UTraceMenuCanvasArt;
class UTraceStrokeText;

/** One frame of the title screen, as ATraceMenuHUD sees it. */
struct FTraceTitleMenuView
{
	static constexpr int32 MaxRows = 8;

	int32 RowCount = 0;
	FTraceMenuRowView Rows[MaxRows];

	/** One line of plain English under the rows, describing the SELECTED row. */
	FString Blurb;

	FString Tagline;
	FString AddressCaption;
	FString AddressValue;

	/** Empty unless UDP 7777 is already taken on this machine, in which case the chip is a lie. */
	FString PortWarning;

	FString FooterKeys;
	FString FooterHint;

	bool bFailureVisible = false;
	FString FailureHeadline;
	FString FailureDetail;
	float FailureFade = 1.f;

	bool bTravelVisible = false;
	FString TravelCaption;
	/** Only a join can sit here for a noticeable time; a local map load is instant. */
	FString TravelHint;

	bool bCursorVisible = false;
	/** 0..1 across the viewport. Fractions, so nothing here depends on the DPI scale. */
	FVector2D CursorFraction = FVector2D(0.5, 0.5);

	float Now = 0.f;
};

/**
 * The title screen. Created by ATraceMenuHUD when `Trace.UI.UseUMG` is on and
 * /Game/Trace/UI/Menu/WBP_TitleMenu loads; absent either, the HUD draws its Canvas path instead and
 * says so in the log.
 */
UCLASS()
class TRACE_API UTraceTitleMenuWidget : public UUserWidget
{
	GENERATED_BODY()

public:
	/** Pushes one frame of state onto the tree. Called once per DrawHUD; makes no decisions. */
	void ApplyView(const FTraceTitleMenuView& InView);

	/**
	 * The row's rectangle in VIEWPORT PIXELS — the space APlayerController::GetMousePosition and
	 * ATraceMenuHUD::RowRects both work in.
	 *
	 * @return false before the row has ever been laid out, which is the first frame and only the
	 *         first frame. The HUD leaves bRowRectsValid false until every row answers, exactly as
	 *         the Canvas path leaves it false until the first DrawMenuRows.
	 */
	bool GetRowViewportRect(int32 InRowIndex, FBox2D& OutRect) const;

	/** How many rows the asset actually provides. Six today; the HUD asserts it matches its enum. */
	int32 GetRowCount() const { return OrderedRows.Num(); }

	//~ Begin UUserWidget interface
	virtual void NativeOnInitialized() override;
	//~ End UUserWidget interface

protected:
	// ---- The art layers, bottom to top -----------------------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuCanvasArt> Backdrop;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceStrokeText> Wordmark;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TaglineText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> AddressChip;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> AddressCaptionText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> AddressValueText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> PortWarningText;

	// ---- The console -----------------------------------------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> ConsolePanel;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowPlay;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowJoin;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowDifficulty;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowMode;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowSettings;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowQuit;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> BlurbText;

	// ---- Footer, frame, cursor -------------------------------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FooterKeysText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FooterHintText;

	/**
	 * ABOVE the footer, deliberately: the footer's dark strip runs to the bottom edge and would
	 * otherwise swallow the frame's bottom rail and two of its corner ticks. Measured on Canvas,
	 * reproduced here by tree order.
	 */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuCanvasArt> Bezel;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuCanvasArt> MenuCursor;

	// ---- The two things that outrank everything else ---------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> TravelOverlay;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceStrokeText> TravelWordmark;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TravelCaptionText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TravelHintText;

	/**
	 * Over the travel overlay, and over the join prompt on the Canvas path. Measured from a
	 * screenshot: drawn earlier, a modal's 78%-black scrim turned the one message the player most
	 * needs to read into a dim brown smudge.
	 */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> FailureBanner;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FailureHeadlineText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FailureDetailText;

private:
	/**
	 * Reproduces the Canvas path's min(width * 0.52, 720) console clamp, which no canvas-panel
	 * anchor can express. See the comment at the call site in ApplyView.
	 */
	void SyncConsoleWidth();

	/** The six rows in ETraceMenuRow order, resolved once. Empty before NativeOnInitialized. */
	UPROPERTY(Transient)
	TArray<TObjectPtr<UTraceMenuRow>> OrderedRows;
};
