// Trace — the title screen as a UMG widget (spec v17 §4).
//
// ---------------------------------------------------------------------------------------------
// WHAT MOVED AND WHAT DID NOT
// ---------------------------------------------------------------------------------------------
// NOTHING about how the title screen BEHAVES moved. ATraceMenuHUD still owns every piece of state
// it owned before — which row is selected, which difficulty, which scoring mode, the press/release
// arming, the cursor-has-moved discriminator, the activation grace period — and still runs every
// one of its harnesses (-TraceAutoPlay, -TraceAutoJoin, -TraceAutoSettings, -TraceMenuClickTest).
// Spec v17 §0: this is a reorganisation, and a behaviour change would be a bug.
//
// What moved is the PIXELS. This widget is a view: once per frame the HUD hands it an
// FTraceTitleMenuView and it puts that on screen. It reads no game state, calls no gameplay code
// and makes no decision. That is what keeps the two renderers honest — they are driven from the
// same state by the same file, so `Trace.UI.VerifyMenu` can compare them.
//
// ---------------------------------------------------------------------------------------------
// HIT TESTING STAYS IN THE HUD, AND THAT IS THE WHOLE TRICK
// ---------------------------------------------------------------------------------------------
// The obvious UMG port makes every row a UButton and lets Slate route the clicks. That would have
// thrown away spec v15 §4's single-press work and the cursor-movement defence in one move, because
// Slate's button semantics are not this menu's semantics.
//
// So this widget is entirely HitTestInvisible and takes no input at all. Instead it reports where
// its rows LANDED — GetRowViewportRect() converts each row's Slate geometry into the same viewport
// pixel space APlayerController::GetMousePosition works in — and ATraceMenuHUD keeps using its own
// RowAtPoint / MousePressed / MouseReleased exactly as written. The click path is the same code on
// both renderers; only the source of the rectangles changes.
//
// ---------------------------------------------------------------------------------------------
// EVERY BindWidget NAME BELOW MUST EXIST IN Content/Trace/UI/Menu/WBP_TitleMenu
// ---------------------------------------------------------------------------------------------
// Rename or delete one in the editor and the Blueprint fails to compile with the missing name in
// the message. That loud failure is the safety net spec v17 §4 asks for, and it is why the asset is
// generated by Scripts/generate-menu-widgets.py from this header's names rather than drawn by hand.

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "Math/Box2D.h"

#include "UI/Widgets/Menu/TraceMenuRowWidget.h"

#include "TraceTitleMenuWidget.generated.h"

class UBorder;
class UImage;
class UTextBlock;
class UTexture2D;
class UTraceAtlasText;
class UTraceMenuGrid;

/**
 * The title block's composition, in the 1080-tall reference pixels the asset is authored in.
 *
 * These numbers ARE spec v20 §0.2's fix, and every one is measured rather than chosen. The two
 * sprites' ink boxes were taken off the artist's sheet ("UI Test Export_2.png"): the wordmark's ink
 * is 14265 x 2200 sheet px, the swoosh's is 18521 x 3729, the swoosh sits 474 sheet px BELOW the
 * mark's ink with its centre 427 px to the LEFT of it. Divide through by the mark's ink width and
 * those become the ratios below. Both sprites are cut so tightly (ink fills 99% of each crop) that
 * the sprite rect and the ink rect are the same rectangle.
 *
 * They lived inside TraceTitleMenuWidget.cpp until the release pass; WP9 made the CANVAS title draw
 * the same sprites at the same places (it is what shows through a modal's scrim), and two copies of
 * a composition is two compositions that drift — the exact reasoning TraceMenuPalette.h records for
 * the palette. Consumed by UTraceTitleMenuWidget::ComposeTitleBlock and ATraceMenuHUD::DrawWordmark.
 */
namespace TraceTitleLayout
{
	/** The mark's width in reference px, and the fraction of a narrow viewport it may not exceed. */
	static constexpr float MarkWidth = 660.f;
	static constexpr float MarkMaxWidthFraction = 0.46f;
	static constexpr float MarkTopY = 46.f;

	/** Swoosh ink / wordmark ink on the sheet is 1.298. Held a shade under it so the mark leads. */
	static constexpr float SwooshWidthOfMark = 1.24f;

	/** The artist's clear space: 474 sheet px / 14265 sheet px of mark = 0.0332. */
	static constexpr float SwooshGapOfMark = 0.033f;

	/** The artist's horizontal offset: 427 / 14265 = 0.0299, to the left. */
	static constexpr float SwooshLeftOfMark = 0.030f;

	/** Reference px the flourish must stop short of the tagline by, if the clamp has to bite. */
	static constexpr float SwooshClearOfTagline = 16.f;

	/**
	 * The swoosh's opacity, down from the authored 0.78.
	 *
	 * It is a backdrop for the title. Even after the WP8.3 re-tone onto the plate palette, a
	 * flourish at full strength competes with the six things on this screen a player actually has
	 * to read.
	 */
	static constexpr float SwooshOpacity = 0.55f;

	/** Where the tagline is authored on the root canvas, reference px. The widget MEASURES the live
	 *  slot and uses this only as the first-frame fallback; the Canvas path draws at it directly. */
	static constexpr float TaglineY = 359.f;
}

/** One frame of the title screen, as ATraceMenuHUD sees it. */
struct FTraceTitleMenuView
{
	static constexpr int32 MaxRows = 8;

	int32 RowCount = 0;
	FTraceMenuRowView Rows[MaxRows];

	/** One line of plain English under the rows, describing the SELECTED row. */
	FString Blurb;

	FString Tagline;
	FString AddressCaption;
	FString AddressValue;

	/** Empty unless UDP 7777 is already taken on this machine, in which case the chip is a lie. */
	FString PortWarning;

	FString FooterKeys;
	FString FooterHint;

	/** WP8.2 — "V 0.1.0   NET xxxxxxxx". The NET half is the cross-play check. The HUD owns the read. */
	FString Version;

	bool bFailureVisible = false;
	FString FailureHeadline;
	FString FailureDetail;
	float FailureFade = 1.f;

	bool bTravelVisible = false;
	FString TravelCaption;
	/** Only a join can sit here for a noticeable time; a local map load is instant. */
	FString TravelHint;

	bool bCursorVisible = false;
	/** 0..1 across the viewport. Fractions, so nothing here depends on the DPI scale. */
	FVector2D CursorFraction = FVector2D(0.5, 0.5);

	float Now = 0.f;
};

/**
 * The title screen. Created by ATraceMenuHUD when `Trace.UI.UseUMG` is on and
 * /Game/Trace/UI/Menu/WBP_TitleMenu loads; absent either, the HUD draws its Canvas path instead and
 * says so in the log.
 */
UCLASS()
class TRACE_API UTraceTitleMenuWidget : public UUserWidget
{
	GENERATED_BODY()

public:
	/** Pushes one frame of state onto the tree. Called once per DrawHUD; makes no decisions. */
	void ApplyView(const FTraceTitleMenuView& InView);

	/**
	 * The row's rectangle in VIEWPORT PIXELS — the space APlayerController::GetMousePosition and
	 * ATraceMenuHUD::RowRects both work in.
	 *
	 * @return false before the row has ever been laid out, which is the first frame and only the
	 *         first frame. The HUD leaves bRowRectsValid false until every row answers, exactly as
	 *         the Canvas path leaves it false until the first DrawMenuRows.
	 */
	bool GetRowViewportRect(int32 InRowIndex, FBox2D& OutRect) const;

	/** How many rows the asset actually provides. Six today; the HUD asserts it matches its enum. */
	int32 GetRowCount() const { return OrderedRows.Num(); }

	/**
	 * Every sprite this screen is supposed to be made of, and whether it actually arrived.
	 *
	 * `Trace.UI.VerifyMenuArt` prints it. It exists because a UImage with no texture in its brush is
	 * drawn by Slate as a plain WHITE RECTANGLE, not as nothing — so a menu missing half the artist's
	 * art does not look broken, it looks like a different design, and nobody investigates.
	 *
	 * @param bIncludeBackdrop  THE RED ARM. Backdrop is the one image on this screen that is SUPPOSED
	 *                          to have no texture — it is a flat black fill — so including it must
	 *                          make this report a missing sprite. If it does not, the "has a texture"
	 *                          test cannot return false and none of its passes mean anything.
	 * @return the number of sprite slots that resolved; @p OutTotal is how many there are.
	 */
	int32 CountResolvedArt(int32& OutTotal, TArray<FString>& OutMissing, bool bIncludeBackdrop = false) const;

	//~ Begin UUserWidget interface
	virtual void NativeOnInitialized() override;
	//~ End UUserWidget interface

protected:
	// ---- The art layers, bottom to top (spec v19 §5) -----------------------------------------------
	//
	// The stroke-drawn backdrop is gone. The brief was explicit — "Keep the background black" — so
	// Backdrop is now a plain black fill and the grid floor, the horizon glow and the bezel that used
	// to sit on it are not drawn at all. What is on the black is the artist's: their swoosh, their
	// wordmark, their buttons, their cursor.
	//
	// SPEC v20: THE TITLE BLOCK'S COMPOSITION IS NOW OWNED BY THIS CLASS, not by the asset. The rects
	// the generator authored put the swoosh through the middle of the wordmark and the footer on top
	// of the blurb, and both are re-derived every frame by ComposeTitleBlock() / PlaceFooterBelowBlurb()
	// from measurements taken off the artist's sheet and off Slate's own layout. Re-running
	// Scripts/generate-menu-widgets.py cannot bring either defect back, and a designer who wants to
	// move the title has to move it HERE — which is stated because the asset's own header claims the
	// opposite for everything else in the tree.

	/** Black. Opaque, and first, so the empty menu map behind it can never show through. */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> Backdrop;

	/** The white sweep from the sheet, behind the title. Decorative; never hit-tested. */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> SwooshImage;

	/**
	 * The TRACE mark, as the artist drew it.
	 *
	 * This replaces UTraceStrokeText, whose five hand-built glyphs were the second of the two reasons
	 * `Trace.UI.UseUMG` was turned off in v17: at the widget path's stroke thickness the R came apart
	 * and the A's point was chopped. A sprite has no thickness to get wrong.
	 */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> Wordmark;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TaglineText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> AddressChip;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> AddressCaptionText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> AddressValueText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> PortWarningText;

	// ---- The console -----------------------------------------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> ConsolePanel;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowPlay;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowJoin;

	/** Spec v19 §2, the practice range. Third, with PLAY and JOIN — see ETraceMenuRow::Practice. */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowPractice;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowDifficulty;

	// RowMode (SCORING MODE) was here. A BindWidget property is a HARD requirement on the asset:
	// leaving it declared after the row was removed from ETraceMenuRow and from
	// Scripts/generate-menu-widgets.py's ROW_NAMES makes WBP_TitleMenu fail to compile with
	// "a required widget binding RowMode was not found", which is the loud failure the discipline at
	// the top of this header exists to produce. All three had to be deleted together.

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowSettings;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTraceMenuRow> RowQuit;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> BlurbText;

	// ---- Footer, frame, cursor -------------------------------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FooterKeysText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FooterHintText;

	/**
	 * The artist's pointer, and the reason the OS cursor is not it.
	 *
	 * Moved by re-anchoring rather than by an offset, so it lands in the same place whatever the DPI
	 * scale is: ATraceMenuHUD hands over a 0..1 fraction of the viewport and this sets the anchor to
	 * it. The sprite's tip is its top-left corner, which is why the alignment is (0,0).
	 */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> MenuCursor;

	// ---- The two things that outrank everything else ---------------------------------------------

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> TravelOverlay;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UImage> TravelWordmark;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TravelCaptionText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> TravelHintText;

	/**
	 * Over the travel overlay, and over the join prompt on the Canvas path. Measured from a
	 * screenshot: drawn earlier, a modal's 78%-black scrim turned the one message the player most
	 * needs to read into a dim brown smudge.
	 */
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UBorder> FailureBanner;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FailureHeadlineText;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UTextBlock> FailureDetailText;

private:
	/**
	 * Reproduces the Canvas path's min(width * 0.52, 720) console clamp, which no canvas-panel
	 * anchor can express. See the comment at the call site in ApplyView.
	 */
	void SyncConsoleWidth();

	// ---- Spec v20 §0.1-0.4: the three title-screen defects this class can reach -------------------
	//
	// All three were AUTHORED defects — the rects and the sprite came out of
	// Scripts/generate-menu-widgets.py and Scripts/slice-ui-assets.py — but a generated asset is not
	// where a fix can be VERIFIED: re-running the generator needs the editor, and the next run of it
	// would silently take a hand-edit back out. So the three fixes live here, in code, in the class
	// that already owns "where the cursor goes" and "how wide the console is", and each one states
	// the number it is enforcing so the asset and this file cannot drift silently.

	/**
	 * DEFECT 1 — the doubled, mis-coloured wordmark, fixed at its actual cause.
	 *
	 * The mark is NOT drawn twice; it is drawn once, and the sprite itself is two-tone. The artist's
	 * TRACE is a NAVY glyph — RGB(29,41,81), byte-identical to the button plates — inside an AMBER
	 * outer glow, and the slicer shipped that crop verbatim onto a pure-black backdrop. On black the
	 * body sits at luminance 45 while the glow reaches 199, so the eye reads the glow as one word and
	 * the dark body as a second, offset one. A Slate tint cannot repair it: a tint MULTIPLIES, so
	 * every colour it can produce is darker than the navy already is.
	 *
	 * So the sprite's own ALPHA is lifted into a new texture: the glyph body becomes ink-white, the
	 * glow keeps the artist's amber at full strength, and the letterforms — which are the part that
	 * is actually the artist's work — are untouched. The result is one mark, in the artist's own
	 * hand, that reads on black.
	 *
	 * SELF-DISABLING. If the sprite ever arrives already legible (a re-slice that lifts the word the
	 * way build_word() lifts PLAY and SETTINGS), the peak-luminance test below finds it and this does
	 * nothing at all. And if the pixels cannot be read — a cooked build that dropped its CPU copy —
	 * it leaves the authored brush alone and says so in the log. Neither case can make the screen
	 * worse than it is today.
	 */
	void LiftWordmarkFromSprite();

	/**
	 * DEFECT 2 — the swoosh cutting through the lettering.
	 *
	 * Not a z-order bug: the mark is already on top. The RECT is the bug. The asset draws the swoosh
	 * 940 wide at y=150 while the mark is 660 wide at y=72, so the brightest object on the screen
	 * (peak luminance 199) crosses the dimmest one 23 px above its baseline.
	 *
	 * The artist's own sheet says what the relationship should be. Measured off "UI Test Export_2.png"
	 * as ink bounding boxes: the swoosh is ~1.30x the mark's ink width and its ink top sits ~22 px
	 * BELOW the mark's ink bottom at this scale, i.e. they do not touch at all. That is what this
	 * reproduces, clamped so the flourish always stops short of the tagline.
	 */
	void ComposeTitleBlock();

	/**
	 * DEFECT 3 — two different strings on one baseline.
	 *
	 * BlurbText lives INSIDE ConsolePanel, so it moves down with the row count; FooterKeysText is a
	 * sibling on the root canvas at a hard-coded y of 958.4, which is the Canvas path's footer
	 * formula evaluated once at 1080p and pasted in. The 7th row (PRACTICE, spec v19 §2) pushed the
	 * blurb onto it — 956.6 against 958.4, 1.8 px apart.
	 *
	 * Fixed by MEASURING rather than by picking a new literal: the footer is placed under the blurb's
	 * actual laid-out bottom every frame, so it cannot collide again the next time a row is added.
	 * The Canvas renderer has the identical collision and hides it under an opaque footer strip
	 * (ATraceMenuHUD::DrawFooter) — it is not a reference to copy.
	 *
	 * IT ALSO PLACES THE PORT-BUSY WARNING, which is the same defect one screen higher and was found
	 * in this pass's own 1280x720 capture: PortWarningText is authored at a fixed y of 436 and the
	 * first row starts at 448.6, so the one line that tells a player their address chip is lying was
	 * drawn across the PLAY button. It is Collapsed unless UDP 7777 is already taken on this machine,
	 * which is why no earlier capture caught it — it took a second process holding the port to make
	 * it appear at all. There is no room for it under the chip on this renderer; the call site says
	 * why, with the measurements.
	 */
	void PlaceFooterBelowBlurb();

	/** The six rows in ETraceMenuRow order, resolved once. Empty before NativeOnInitialized. */
	UPROPERTY(Transient)
	TArray<TObjectPtr<UTraceMenuRow>> OrderedRows;

	// ---- SPEC v23 §A1: THE SCROLLING GRID -----------------------------------------------------------
	//
	// The owner asked for "something like the scrolling background grid that used to be in the main
	// menu ui". It still exists on the Canvas renderer (ATraceMenuHUD::DrawGridFloor); spec v19 §5 gave
	// THIS screen a flat black backdrop and the grid stopped being on the screen anybody sees.

	/**
	 * Adds UTraceMenuGrid to the root canvas, directly above Backdrop and below every other layer.
	 *
	 * WHY THIS IS CODE AND NOT Scripts/generate-menu-widgets.py. Every other widget on this screen is
	 * authored by the generator, and the obvious thing would have been to author this one too. Three
	 * reasons not to, and the third is the one that decides it:
	 *
	 *   1. the generator needs the editor to run, so a grid that only exists once somebody re-runs it
	 *      is a grid that is missing from every checkout until they do;
	 *   2. it would put a UWidget subclass in the .uasset with no BindWidget contract behind it, so a
	 *      rename in C++ would fail silently in the asset rather than loudly at compile time — the
	 *      exact failure the BindWidget discipline at the top of this header exists to prevent;
	 *   3. THE Z-ORDER IS A CORRECTNESS PROPERTY, not a styling one. This screen's only opaque layers
	 *      are the row plates; ConsolePanel is a CLEAR border, so the blurb, both footer lines and the
	 *      tagline sit on bare black with nothing between them and whatever is behind. The grid must
	 *      therefore be provably BELOW all of them, and "provably" means a slot z-order set next to
	 *      the Backdrop's own, in one place, in a file that fails to compile if Backdrop is renamed —
	 *      not a number typed into a Python script that nobody re-runs.
	 *
	 * Idempotent, and a no-op if the asset ever gains a Backdrop that is not on a canvas panel.
	 */
	void InstallGridBackground();

	/** The grid, once installed. Null if the install found no canvas to put it on; never fatal. */
	UPROPERTY(Transient)
	TObjectPtr<UTraceMenuGrid> GridFloor;

	// ---- WP8.2: THE VERSION STRING, bottom-right ----------------------------------------------------

	/**
	 * Adds a small atlas-text label to the root canvas for the view's Version string. Code rather
	 * than Scripts/generate-menu-widgets.py for exactly InstallGridBackground()'s reasons — chiefly
	 * that a label which only exists once somebody re-runs the generator is a label missing from
	 * every checkout until they do. Idempotent; a failure leaves the corner empty, never fatal.
	 */
	void InstallVersionLabel();

	/** The label, once installed. Null if the install found no canvas; never fatal. */
	UPROPERTY(Transient)
	TObjectPtr<UTraceAtlasText> VersionLabel;

	// ---- SPEC v22 §A1: THE WHOLE SCREEN IS ONE TYPEFACE ---------------------------------------------
	//
	// The rows retire their own word sprites (UTraceMenuRow::ApplyView). These are everything ELSE on
	// the title screen with letters in it — the tagline, the address chip, the port warning, the
	// blurb, both footer lines, the travel card and the failure banner — moved onto the same
	// Sofachrome atlas, so the screen has no second face left anywhere on it.
	//
	// Each UTextBlock stays as the model and keeps receiving exactly the SetText it always did; a
	// UTraceAtlasText draws it from the atlas. See UI/Text/TraceAtlasTextSwap.h.

	/** Installed once, on the first ApplyView. */
	bool bAtlasLabelsInstalled = false;

	UPROPERTY(Transient)
	TArray<FTraceAtlasLabel> AtlasLabels;

	/** Idempotent; anything that fails leaves that one authored text block drawing as before. */
	void InstallAtlasLabels();

	/**
	 * The widget actually in the panel for @p Block — the atlas label if it was swapped, else
	 * @p Block itself. Anything asking a text block for its Slot or its geometry must go through
	 * this; TraceAtlasTextSwap::Live explains why.
	 */
	UWidget* LiveText(UTextBlock* Block) const { return TraceAtlasTextSwap::Live(AtlasLabels, Block); }

	/**
	 * The recoloured mark from LiftWordmarkFromSprite(), kept alive by being a UPROPERTY.
	 *
	 * It is a transient texture in the transient package: nothing else in the reference graph holds
	 * it, so a raw pointer would be collected out from under the title screen on the first GC.
	 */
	UPROPERTY(Transient)
	TObjectPtr<UTexture2D> LiftedWordmark;

	/** LiftWordmarkFromSprite() has run. It runs once, whatever its outcome was. */
	bool bWordmarkLiftAttempted = false;
};
